package convert

// bookkeeping_test.go — a user-role record no person typed never becomes a
// prompt row; one a person did type still does.

import (
	"strings"
	"testing"

	storev1 "agentrepl/proto/store/v1"
)

// promptRows are the entries that would draw a USER PROMPT bubble: a served
// prompt page line, or anything keyed in the prompt space.
func promptRows(entries []*storev1.StoreEntry) []*storev1.StoreEntry {
	var rows []*storev1.StoreEntry
	for _, e := range entries {
		if pageLine(e).GetAgentItem().GetAgentPrompt() != nil || strings.HasPrefix(e.GetUpsertKey(), "prompt:") {
			rows = append(rows, e)
		}
	}
	return rows
}

// promptText reads the one text block of a served prompt row.
func promptText(t *testing.T, e *storev1.StoreEntry) string {
	t.Helper()
	blocks := pageLine(e).GetAgentItem().GetAgentPrompt().GetSaid().GetContent().GetBlocks()
	if len(blocks) != 1 {
		t.Fatalf("prompt blocks = %d, want 1: %v", len(blocks), blocks)
	}
	return blocks[0].GetText().GetText()
}

// recordUUID reads a fixture line's own uuid.
func recordUUID(t *testing.T, line string) string {
	t.Helper()
	return str(decode(t, line)["uuid"])
}

func TestCapturedBookkeepingIsWithheldNeverPrompted(t *testing.T) {
	tests := []struct {
		name     string
		fixture  string
		wantKind string
	}{
		{name: "a local command's envelope", fixture: "transcript-lines/user-slash-command.jsonl", wantKind: kindUserSlashCommand},
		{name: "a session command typed bare", fixture: "transcript-lines/user-slash-command-bare.jsonl", wantKind: kindUserSlashCommand},
		{name: "a local command's printed output", fixture: "transcript-lines/user-local-command-stdout.jsonl", wantKind: kindUserLocalCommandOutput},
		{name: "the compaction notice a /compact prints", fixture: "transcript-lines/user-local-command-stdout-compacted.jsonl", wantKind: kindUserLocalCommandOutput},
		{name: "the interrupt marker", fixture: "transcript-lines/user-interrupt.jsonl", wantKind: kindUserInterrupt},
		{name: "a task notification this stream launched nothing for", fixture: "transcript-lines/user-task-notification.jsonl", wantKind: kindUserTaskNotification},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Arrange.
			c := newTestConverter(t)
			line := corpusLine(t, tc.fixture)

			// Act.
			entries := convertLines(t, c, line)

			// Assert.
			if rows := promptRows(entries); len(rows) != 0 {
				t.Fatalf("minted %d prompt row(s) for a line no person typed: %v", len(rows), allKeys(rows))
			}
			if len(entries) != 1 {
				t.Fatalf("entries = %d, want 1", len(entries))
			}
			if got := vendorKindOf(entries[0]); got != tc.wantKind {
				t.Fatalf("kind = %q, want %q", got, tc.wantKind)
			}
		})
	}
}

func TestWithheldBookkeepingKeysOnTheRecordUUIDTheStreamPlaneKeysOn(t *testing.T) {
	// Arrange. The stream plane keys residue `residue:<vendor record uuid>`, so a
	// fact both planes see as residue collapses onto one row.
	c := newTestConverter(t)
	line := corpusLine(t, "transcript-lines/user-local-command-stdout.jsonl")

	// Act.
	entries := convertLines(t, c, line)

	// Assert.
	if got, want := entries[0].GetUpsertKey(), "residue:"+recordUUID(t, line); got != want {
		t.Fatalf("upsert key = %q, want %q", got, want)
	}
}

func TestCaveatedCommandTheSchemaDoesNotNameIsStillWithheld(t *testing.T) {
	// Arrange. `/effort` is answered by the CLI itself but is not in the
	// SessionCommand table; the caveat the CLI writes before it is what says so.
	c := newTestConverter(t)
	caveat := `{"type":"user","uuid":"cav-1","isMeta":true,"isSidechain":false,"entrypoint":"cli","timestamp":"` + ts1 +
		`","message":{"role":"user","content":"<local-command-caveat>Caveat: generated by local commands.</local-command-caveat>"}}`
	envelope := `{"type":"user","uuid":"env-1","parentUuid":"cav-1","isSidechain":false,"entrypoint":"cli","timestamp":"` + ts1 +
		`","message":{"role":"user","content":"<command-name>/effort</command-name>\n  <command-message>effort</command-message>\n  <command-args>medium</command-args>"}}`

	// Act.
	entries := convertLines(t, c, caveat, envelope)

	// Assert.
	if rows := promptRows(entries); len(rows) != 0 {
		t.Fatalf("minted %d prompt row(s) for a caveated local command", len(rows))
	}
	if got := vendorKindOf(entries[1]); got != kindUserSlashCommand {
		t.Fatalf("kind = %q, want %q", got, kindUserSlashCommand)
	}
}

func TestPromptCommandIsServedAsTheTextThePersonTyped(t *testing.T) {
	// Arrange. A custom command expands into a prompt for the agent; its envelope
	// carries no local-command caveat and names no session command.
	c := newTestConverter(t)
	line := corpusLine(t, "transcript-lines/user-prompt-command.jsonl")

	// Act.
	entries := convertLines(t, c, line)

	// Assert.
	rows := promptRows(entries)
	if len(rows) != 1 {
		t.Fatalf("prompt rows = %d, want 1", len(rows))
	}
	if got := promptText(t, rows[0]); !strings.HasPrefix(got, "/loop iteration") || strings.Contains(got, "<command-") {
		t.Fatalf("prompt text = %q, want the typed `/loop …` with no envelope markup", got)
	}
}

func TestPastedContentPromptStaysAPromptVerbatim(t *testing.T) {
	// Arrange. `<pasted_content …>` is the CLI's rendering of text a person pasted
	// into a prompt they typed.
	c := newTestConverter(t)
	line := corpusLine(t, "transcript-lines/user-pasted-content.jsonl")
	want := str(obj(decode(t, line)["message"])["content"])

	// Act.
	entries := convertLines(t, c, line)

	// Assert.
	rows := promptRows(entries)
	if len(rows) != 1 {
		t.Fatalf("prompt rows = %d, want 1", len(rows))
	}
	if got := promptText(t, rows[0]); got != want {
		t.Fatalf("prompt text = %q, want the record's content verbatim %q", got, want)
	}
}

func TestEnvelopeQuotedInsideProseStaysAPrompt(t *testing.T) {
	// Arrange. Prose around the envelope means the person QUOTED a command.
	c := newTestConverter(t)
	line := externalPromptLine("u1", "cli", "why did <command-name>/compact</command-name> run?")

	// Act.
	entries := convertLines(t, c, line)

	// Assert.
	if rows := promptRows(entries); len(rows) != 1 {
		t.Fatalf("prompt rows = %d, want 1", len(rows))
	}
}

func TestNotificationMarkupAPersonTypedStaysAPrompt(t *testing.T) {
	// Arrange. The record states `origin.kind: "human"`: the vendor's own word
	// wins over the shape of what was typed.
	c := newTestConverter(t)
	line := `{"type":"user","uuid":"u1","isSidechain":false,"entrypoint":"cli","origin":{"kind":"human"},"timestamp":"` + ts1 +
		`","message":{"role":"user","content":"<task-notification>\n<status>completed</status>\n</task-notification>"}}`

	// Act.
	entries := convertLines(t, c, line)

	// Assert.
	if rows := promptRows(entries); len(rows) != 1 {
		t.Fatalf("prompt rows = %d, want 1", len(rows))
	}
}

func TestUnmodelledNonHumanOriginIsUnknownResidueNeverAPrompt(t *testing.T) {
	// Arrange. An origin kind that names no person and no modelled source.
	c := newTestConverter(t)
	line := `{"type":"user","uuid":"u1","isSidechain":false,"entrypoint":"cli","origin":{"kind":"scheduler"},"timestamp":"` + ts1 +
		`","message":{"role":"user","content":"wake up"}}`

	// Act.
	entries := convertLines(t, c, line)

	// Assert.
	if rows := promptRows(entries); len(rows) != 0 {
		t.Fatalf("minted %d prompt row(s) for a non-human origin", len(rows))
	}
	unknown := entries[0].GetAgentUpdate().GetUnservedItem().GetUnknown()
	if unknown.GetDiscriminatorField() != "origin.kind" || unknown.GetDiscriminator() != "scheduler" {
		t.Fatalf("unknown = %v, want origin.kind=scheduler", unknown)
	}
}
