// mock_helpers_test.go — FIXTURES GENERATED BY THE REAL MOCKED VENDOR.
//
// Every other file in this package builds its vendor tree by hand, line by
// line, from testdata/corpus. This file does something different and stronger:
// it RUNS the shim's own `--fake` mocked vendor (agent-shim/claude/shim, built
// from source once per test binary) and lets IT write the transcripts, the
// subagent transcripts and metas, and the task spools. Nothing here copies a
// vendor file; the mock is the only author, exactly as it is in production.
//
// That is the whole point of the exercise: the sidecar's converter is then
// facing the SAME bytes the shim's own scenario suite faces, so a disagreement
// between the two planes shows up as a failing subject here rather than as a
// silent divergence in the field.
//
// The composition per scenario:
//
//  1. a THROWAWAY real store for the SHIM's stream-plane writes — the shim is a
//     store producer too, and its rows must never contaminate what this suite
//     asserts about the sidecar's file-plane rows. See mockVendorStore below.
//  2. `node <shim>/dist/main.js --listen <uds> --store-socket <throwaway>
//     --log-fd 3 --fake`, cwd = a private workspace, CLAUDE_CONFIG_DIR and
//     AGENT_REPL_FAKE_SPOOL_ROOT pointed at private trees.
//  3. shim.v1 over that socket: StartSession{fresh}, StartTurn{the `!name`
//     prompt}, wait on WatchAgent for the turn's terminal, KillSession{force}.
//  4. the REAL store and the REAL sidecar (the ordinary harness) over the tree
//     the mock just wrote.
//
// SYNCHRONIZATION IS ALWAYS A REAL SIGNAL, as everywhere else in this package:
// a WatchAgent frame, a process exit, a bounded ticker-driven re-read of a
// durable surface. There is no time.Sleep here either.
package integration

import (
	"context"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"math/rand"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"syscall"
	"testing"
	"time"

	"connectrpc.com/connect"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
	"google.golang.org/protobuf/proto"

	conversationv1 "agentrepl/proto/conversation/v1"
	shimv1 "agentrepl/proto/shim/v1"
	"agentrepl/proto/shim/v1/shimv1connect"
	storev1 "agentrepl/proto/store/v1"
	"agentrepl/proto/store/v1/storev1connect"
)

// ---------------------------------------------------------------------------
// Building the mocked vendor.
// ---------------------------------------------------------------------------

// standDownGrace bounds how long a generated scenario waits for the mocked
// vendor to leave after SIGTERM before killing it.
const standDownGrace = 10 * time.Second

var (
	mockShimOnce sync.Once
	mockShimMain string
	mockShimErr  error
)

// mockShimDir is the shim package's root — READ-ONLY to this suite. Nothing
// here ever writes under it except the `npm ci` / `npm run build` the shim's
// own AGENTS.md documents.
func mockShimDir() string {
	return filepath.Join(repo.agentShimDir, "claude", "shim")
}

// mockShimEntry builds the shim once per test binary and answers the bundle's
// path. A machine without node or npm SKIPS the whole mock package loudly: the
// mocked vendor is a Node program, and pretending to test it without one would
// be a green run that proved nothing.
func mockShimEntry(t *testing.T) string {
	t.Helper()
	for _, tool := range []string{"node", "npm"} {
		if _, err := exec.LookPath(tool); err != nil {
			t.Skipf("SKIPPING the mocked-vendor subjects: %q is not on PATH, and the mock IS a Node program — "+
				"these fixtures are generated by running it, never by copying files (%v)", tool, err)
		}
	}
	mockShimOnce.Do(func() { mockShimMain, mockShimErr = buildMockShim() })
	if mockShimErr != nil {
		t.Fatalf("the mocked vendor does not build, so no fixture can be generated: %v", mockShimErr)
	}
	return mockShimMain
}

func buildMockShim() (string, error) {
	dir := mockShimDir()
	if _, err := os.Stat(filepath.Join(dir, "node_modules")); errors.Is(err, fs.ErrNotExist) {
		if out, err := runIn(dir, "npm", "ci", "--no-audit", "--no-fund"); err != nil {
			return "", fmt.Errorf("npm ci in %s: %v\n%s", dir, err, out)
		}
	} else if err != nil {
		return "", fmt.Errorf("stat %s/node_modules: %w", dir, err)
	}
	if out, err := runIn(dir, "npm", "run", "build"); err != nil {
		return "", fmt.Errorf("npm run build in %s: %v\n%s", dir, err, out)
	}
	entry := filepath.Join(dir, "dist", "main.js")
	if _, err := os.Stat(entry); err != nil {
		return "", fmt.Errorf("the build produced no bundle at %s: %w", entry, err)
	}
	return entry, nil
}

func runIn(dir, name string, args ...string) (string, error) {
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	return string(out), err
}

// ---------------------------------------------------------------------------
// One generated vendor tree.
// ---------------------------------------------------------------------------

// mockTree is what one scenario run left on disk, plus the roots the sidecar
// must be pointed at to read it.
//
// SESSION IDS ARE DISCOVERED, NEVER COMPUTED. The cwd slug is a lossy mapping
// and the mock resolves its own cwd (macOS's /var → /private/var), so the tree
// is enumerated after the run rather than predicted before it. A rotation
// scenario therefore reports BOTH identities without the harness knowing in
// advance that it rotated.
type mockTree struct {
	ConfigRoot string // the sidecar's --config-roots entry (CLAUDE_CONFIG_DIR)
	SpoolRoot  string // the sidecar's --spool-root (parent of claude-<uid>)
	FakeSpool  string // what the mock was given: <SpoolRoot>/claude-<uid>
	Cwd        string // the workspace the mock ran in
	LogPath    string // the shim's own log (fd 3), for evidence in failures

	// VendorSessionID is what StartSession reported: the session the turn ran
	// under. After a rotation the LAST transcript is a different id.
	VendorSessionID string

	// Transcripts is every `<session>.jsonl` the mock wrote, sorted by mtime
	// (oldest first). Each basename is a MAIN AGENT ID under R9.
	Transcripts []string

	// Subagents is every `agent-<id>.jsonl` under any session's subagents dir.
	Subagents []string

	// Spools is every `<task>.output` the mock wrote.
	Spools []string
}

// MainAgentIDs answers the R9 main-agent identity of every transcript: the
// FILE's session uuid, never the per-record sessionId.
func (m *mockTree) MainAgentIDs() []string {
	ids := make([]string, 0, len(m.Transcripts))
	for _, p := range m.Transcripts {
		ids = append(ids, strings.TrimSuffix(filepath.Base(p), ".jsonl"))
	}
	return ids
}

// LastMainAgentID is the identity in force when the turn ended — the same as
// VendorSessionID except in a rotation scenario, where the turn's tail belongs
// to the NEW identity.
func (m *mockTree) LastMainAgentID() string {
	ids := m.MainAgentIDs()
	if len(ids) == 0 {
		return ""
	}
	return ids[len(ids)-1]
}

// SubagentIDs answers each subagent transcript's vendor agent id — the
// `agent-<id>` file name, which is also the sidechain records' `agentId`.
func (m *mockTree) SubagentIDs() []string {
	ids := make([]string, 0, len(m.Subagents))
	for _, p := range m.Subagents {
		ids = append(ids, strings.TrimSuffix(strings.TrimPrefix(filepath.Base(p), "agent-"), ".jsonl"))
	}
	sort.Strings(ids)
	return ids
}

// ShellSpoolTaskIDs answers the `b*` task ids — the DETACHED SHELL spools.
func (m *mockTree) ShellSpoolTaskIDs() []string {
	return m.spoolTaskIDs("b")
}

// AgentSpoolTaskIDs answers the `a*` task ids — the backgrounded AGENT spools.
func (m *mockTree) AgentSpoolTaskIDs() []string {
	return m.spoolTaskIDs("a")
}

func (m *mockTree) spoolTaskIDs(prefix string) []string {
	var out []string
	for _, p := range m.Spools {
		id := strings.TrimSuffix(filepath.Base(p), ".output")
		if strings.HasPrefix(id, prefix) {
			out = append(out, id)
		}
	}
	sort.Strings(out)
	return out
}

// ---------------------------------------------------------------------------
// Driving one scenario.
// ---------------------------------------------------------------------------

// mockWait says what ends the drive for a scenario.
type mockWait int

const (
	// waitTerminal — the ordinary case: the turn reaches AgentSuccess or
	// AgentFailure on the main agent's WatchAgent stream.
	waitTerminal mockWait = iota
	// waitEntries — a scenario whose turn deliberately NEVER terminates
	// (`!hold`, `!query-eof`, `!query-fail`, the live detached ones). The
	// drive ends when the stream has delivered at least one entry, which is
	// still a real signal and never a duration.
	waitEntries
)

// generateMock runs ONE scenario through the real mocked vendor and answers the
// tree it wrote.
func generateMock(t *testing.T, prompt string, wait mockWait) *mockTree {
	t.Helper()
	entry := mockShimEntry(t)

	base := t.TempDir()
	tree := &mockTree{
		ConfigRoot: filepath.Join(base, "config"),
		SpoolRoot:  filepath.Join(base, "spool"),
		Cwd:        filepath.Join(base, "work"),
		LogPath:    filepath.Join(base, "shim.log"),
	}
	tree.FakeSpool = filepath.Join(tree.SpoolRoot, "claude-"+spoolUID)
	for _, d := range []string{tree.ConfigRoot, tree.FakeSpool, tree.Cwd, filepath.Join(base, "state"), filepath.Join(base, "lock")} {
		mustMkdirAll(t, d)
	}
	// The mock resolves its own cwd; comparing an unresolved one against a
	// discovered path would fail on macOS, where /var is a symlink.
	tree.Cwd = resolved(tree.Cwd)

	// The shim's OWN store: a throwaway. The shim writes the stream plane, and
	// mixing those rows into the store this suite reads back would mean a
	// sidecar assertion could pass on a row the SHIM wrote.
	vendorStore := startRealStore(t)

	logFile, err := os.Create(tree.LogPath)
	if err != nil {
		t.Fatalf("create the mocked vendor's log: %v", err)
	}
	t.Cleanup(func() { _ = logFile.Close() })

	socket := shortSocketPath(t, "fakeshim")
	cmd := exec.Command("node", entry,
		"--listen", socket,
		"--store-socket", vendorStore.Socket,
		"--log-fd", "3",
		"--fake",
	)
	cmd.Dir = tree.Cwd
	cmd.ExtraFiles = []*os.File{logFile} // becomes fd 3 in the child
	cmd.Env = append(os.Environ(),
		"CLAUDE_CONFIG_DIR="+tree.ConfigRoot,
		"AGENT_REPL_FAKE_SPOOL_ROOT="+tree.FakeSpool,
		"AGENT_REPL_STATE_DIR="+filepath.Join(base, "state"),
		"AGENT_REPL_LOCK_DIR="+filepath.Join(base, "lock"),
		"AGENT_REPL_STORE_SOCKET="+vendorStore.Socket,
		"AGENT_REPL_OWNED=1",
		"SHIM_BUILD_SHA=test",
		"AGENT_REPL_FORBID_VENDOR_CALLS=1",
	)
	cmd.Stdout = os.Stderr
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		t.Fatalf("spawn the mocked vendor: %v", err)
	}
	done := make(chan error, 1)
	go func() { done <- cmd.Wait() }()
	stopped := false
	stop := func() {
		if stopped {
			return
		}
		stopped = true
		if cmd.Process != nil {
			_ = cmd.Process.Kill()
		}
		<-done
	}
	t.Cleanup(stop)

	ctx, cancel := testContext(t)
	defer cancel()
	awaitSocket(ctx, t, socket, tree)

	httpClient := udsHTTPClient(socket)
	client := shimv1connect.NewShimClient(httpClient, "http://shim")
	agent := startMockSession(ctx, t, client, tree)
	tree.VendorSessionID = agent.vendorSessionID
	driveMockTurn(ctx, t, client, prompt, agent.agentID, wait, tree)

	// KillSession{force} is the authorized stand-down: it interrupts whatever is
	// still live and lets the mock finish writing its files. It does NOT end the
	// process — the shim outlives its daemon by design, and SIGTERM is its one
	// authorized shutdown — so the stand-down is followed by SIGTERM, and the
	// process EXIT is the signal that the tree is complete.
	// Every connection this drive opened is dropped BEFORE the stand-down: a
	// server with a live socket does not stop serving, so a lingering pooled
	// connection would turn the stand-down into a hang that looks like a mock
	// defect and is not one.
	httpClient.CloseIdleConnections()
	//
	// SIGTERM IS THE STAND-DOWN, not a bare kill: the shim's contract makes
	// SIGTERM take the `KillSession{force:true}` path internally and then exit 0.
	// Calling the rpc first and signalling second would be the same stand-down
	// twice, and the rpc does not return while the process is still serving the
	// streams this drive opened.
	if cmd.Process != nil {
		_ = cmd.Process.Signal(syscall.SIGTERM)
	}
	select {
	case <-done:
		stopped = true
	case <-time.After(standDownGrace):
		// The stand-down is bounded, not awaited forever: the mock writes every
		// vendor file synchronously (appendFileSync), so the tree is already
		// complete by the time the turn's terminal was observed, and a mock that
		// will not leave must not hold the whole suite. The kill is reported so a
		// stand-down regression is visible rather than absorbed.
		t.Logf("the mocked vendor did not leave within %s of SIGTERM; killing it. Its log tail:\n%s",
			standDownGrace, mockLogTail(tree.LogPath))
		if cmd.Process != nil {
			_ = cmd.Process.Kill()
		}
		<-done
		stopped = true
	}

	enumerateMockTree(t, tree)
	return tree
}

func phase(t *testing.T, name string) {
	t.Logf("PHASE %s at %s", name, time.Now().Format(time.StampMilli))
}

func awaitSocket(ctx context.Context, t *testing.T, socket string, tree *mockTree) {
	t.Helper()
	tick := time.NewTicker(pollTick)
	defer tick.Stop()
	for {
		if _, err := os.Stat(socket); err == nil {
			return
		}
		select {
		case <-ctx.Done():
			t.Fatalf("the mocked vendor never bound %s; its log is at %s", socket, tree.LogPath)
		case <-tick.C:
		}
	}
}

type mockSession struct {
	vendorSessionID string
	agentID         *conversationv1.AgentId
}

func startMockSession(ctx context.Context, t *testing.T, c shimv1connect.ShimClient, tree *mockTree) mockSession {
	t.Helper()
	resp, err := c.StartSession(ctx, connect.NewRequest(&shimv1.StartSessionRequest{
		Source: &shimv1.StartSessionRequest_Fresh{Fresh: &shimv1.StartSessionFresh{
			// Both fields are non-optional, so both are set: the validation
			// invariant makes an unset one illegal, not defaulted.
			Model: &conversationv1.AgentModel{Name: "claude-opus-5"},
			PermissionMode: &conversationv1.AgentPermissionMode{
				Mode: &conversationv1.AgentPermissionMode_Bypass{Bypass: &conversationv1.AgentPermissionModeBypass{}},
			},
		}},
	}))
	if err != nil {
		t.Fatalf("StartSession on the mocked vendor: %v (log: %s)", err, tree.LogPath)
	}
	success := resp.Msg.GetSuccess()
	if success == nil {
		t.Fatalf("StartSession was refused: %v (log: %s)", resp.Msg.GetFailure(), tree.LogPath)
	}
	return mockSession{vendorSessionID: success.GetSession().GetVendorSessionId()}
}

func driveMockTurn(
	ctx context.Context,
	t *testing.T,
	c shimv1connect.ShimClient,
	prompt string,
	_ *conversationv1.AgentId,
	wait mockWait,
	tree *mockTree,
) {
	t.Helper()
	turnID := &conversationv1.TurnId{Value: "turn-" + randomHex()}
	resp, err := c.StartTurn(ctx, connect.NewRequest(&shimv1.StartTurnRequest{
		Turn: turnID,
		Said: &conversationv1.UserSaid{Content: &conversationv1.UserContent{
			Blocks: []*conversationv1.UserContentBlock{{
				Block: &conversationv1.UserContentBlock_Text{
					Text: &conversationv1.TextBlock{Text: prompt},
				},
			}},
		}},
		Origin:   conversationv1.PromptOrigin_PROMPT_ORIGIN_USER_SENT,
		PageSize: 200,
	}))
	if err != nil {
		t.Fatalf("StartTurn(%q): %v (log: %s)", prompt, err, tree.LogPath)
	}
	success := resp.Msg.GetSuccess()
	if success == nil {
		t.Fatalf("StartTurn(%q) was refused: %v (log: %s)", prompt, resp.Msg.GetFailure(), tree.LogPath)
	}
	awaitMockTurnEnd(ctx, t, c, success.GetPrompt().GetAgent(), wait, prompt, tree)
}

// awaitMockTurnEnd tails the main agent and returns on the turn's terminal —
// or, for a scenario that deliberately never terminates, on the first entry.
func awaitMockTurnEnd(
	ctx context.Context,
	t *testing.T,
	c shimv1connect.ShimClient,
	target *conversationv1.AgentId,
	wait mockWait,
	prompt string,
	tree *mockTree,
) {
	t.Helper()
	// WatchAgent is a STANDING stream: it never concludes on its own, because
	// the terminal fact rides the entries and the caller closes when it stops
	// caring. Closing it therefore means CANCELLING it — a plain Close would
	// wait for a server that has no reason to hang up, which reads as a hang
	// and is really just the contract.
	watchCtx, closeWatch := context.WithCancel(ctx)
	defer closeWatch()
	stream, err := c.WatchAgent(watchCtx, connect.NewRequest(&shimv1.WatchAgentRequest{
		Target:   target,
		PageSize: 200,
	}))
	if err != nil {
		t.Fatalf("WatchAgent for %q: %v (log: %s)", prompt, err, tree.LogPath)
	}

	seen := 0
	for stream.Receive() {
		switch frame := stream.Msg().GetFrame().(type) {
		case *shimv1.WatchAgentResponse_Page:
			for _, e := range frame.Page.GetEntries() {
				seen++
				if isMockTerminal(e.GetEntry()) && wait == waitTerminal {
					return
				}
			}
		case *shimv1.WatchAgentResponse_Entry:
			seen++
			if isMockTerminal(stream.Msg().GetEntry().GetEntry()) && wait == waitTerminal {
				return
			}
		}
		if wait == waitEntries && seen > 0 {
			return
		}
	}
	if err := stream.Err(); err != nil && ctx.Err() == nil {
		t.Fatalf("WatchAgent for %q ended: %v (log: %s)", prompt, err, tree.LogPath)
	}
	if wait == waitTerminal {
		t.Fatalf("the turn for %q never reached a terminal frame (log: %s)", prompt, tree.LogPath)
	}
}

// isMockTerminal answers whether an entry is a turn terminal — the success or
// failure arm of an AgentFrame, which is exactly what agent.proto declares as
// "the agent ended".
func isMockTerminal(entry *conversationv1.HistoryEntry) bool {
	frame := entry.GetAgentFrame()
	if frame == nil {
		return false
	}
	switch frame.GetResult().(type) {
	case *conversationv1.AgentFrame_Success, *conversationv1.AgentFrame_Failure:
		return true
	default:
		return false
	}
}

func randomHex() string {
	b := make([]byte, 6)
	// A test-local id needs to be unique within one process, not unguessable.
	for i := range b {
		b[i] = byte(rand.Intn(256))
	}
	return hex.EncodeToString(b)
}

// enumerateMockTree walks what the mock wrote. It is the ONLY source of the
// tree's shape: nothing here predicts a path.
func enumerateMockTree(t *testing.T, tree *mockTree) {
	t.Helper()
	type stamped struct {
		path string
		mod  time.Time
	}
	var transcripts []stamped
	projects := filepath.Join(tree.ConfigRoot, "projects")
	err := filepath.WalkDir(projects, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".jsonl") {
			return nil
		}
		info, statErr := d.Info()
		if statErr != nil {
			return statErr
		}
		if filepath.Base(filepath.Dir(path)) == "subagents" {
			tree.Subagents = append(tree.Subagents, path)
			return nil
		}
		transcripts = append(transcripts, stamped{path: path, mod: info.ModTime()})
		return nil
	})
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("walking the generated transcript tree %s: %v", projects, err)
	}
	sort.Slice(transcripts, func(i, j int) bool { return transcripts[i].mod.Before(transcripts[j].mod) })
	for _, s := range transcripts {
		tree.Transcripts = append(tree.Transcripts, s.path)
	}
	sort.Strings(tree.Subagents)

	err = filepath.WalkDir(tree.SpoolRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(path, ".output") {
			tree.Spools = append(tree.Spools, path)
		}
		return nil
	})
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("walking the generated spool tree %s: %v", tree.SpoolRoot, err)
	}
	sort.Strings(tree.Spools)
}

// ---------------------------------------------------------------------------
// Ingesting a generated tree with the REAL store and the REAL sidecar.
// ---------------------------------------------------------------------------

// proxyStore is a RECORDING PASS-THROUGH in front of the real store.
//
// Why it exists: the residue arms (`unparsed`, `unknown`, `vendor_specific`)
// are DURABLE but have no read verb — store/v1 serves pages, bash runs, live
// work and cursors, and nothing enumerates unserved items. A subject that must
// assert "this scenario produced ZERO unparsed residue" therefore has to read
// the WIRE. The proxy records every `WriteBatch` and forwards it verbatim, so
// the same run is both fully visible on the wire AND fully durable in the real
// store, and the book/bash assertions still read back through the store's own
// verbs.
//
// It implements the two verbs the sidecar's contract allows it to call and
// nothing else: a sidecar reaching any other verb is a contract violation, and
// an `unimplemented` answer states that instead of hiding it.
type proxyStore struct {
	t      *testing.T
	Socket string
	up     storev1connect.ShimStoreClient

	mu      sync.Mutex
	batches []*storev1.WriteBatchRequest

	srv     *http.Server
	ln      net.Listener
	done    chan struct{}
	stopped bool
}

var _ storev1connect.ShimStoreHandler = (*proxyStore)(nil)

func startProxyStore(t *testing.T, upstream string) *proxyStore {
	t.Helper()
	socket := shortSocketPath(t, "proxy")
	p := &proxyStore{t: t, Socket: socket, up: storeClient(upstream), done: make(chan struct{})}
	mux := http.NewServeMux()
	path, handler := storev1connect.NewShimStoreHandler(p)
	mux.Handle(path, handler)
	ln, err := net.Listen("unix", socket)
	if err != nil {
		t.Fatalf("listen on %s: %v", socket, err)
	}
	p.ln = ln
	p.srv = &http.Server{Handler: h2c.NewHandler(mux, &http2.Server{})}
	go func() {
		defer close(p.done)
		_ = p.srv.Serve(ln)
	}()
	t.Cleanup(p.Stop)
	return p
}

func (p *proxyStore) Stop() {
	p.t.Helper()
	p.mu.Lock()
	if p.stopped {
		p.mu.Unlock()
		return
	}
	p.stopped = true
	p.mu.Unlock()
	ctx, cancel := context.WithTimeout(context.Background(), waitBudget)
	defer cancel()
	_ = p.srv.Shutdown(ctx)
	<-p.done
	os.Remove(p.Socket)
}

func (p *proxyStore) WriteBatch(ctx context.Context, req *connect.Request[storev1.WriteBatchRequest]) (*connect.Response[storev1.WriteBatchResponse], error) {
	p.mu.Lock()
	p.batches = append(p.batches, proto.Clone(req.Msg).(*storev1.WriteBatchRequest))
	p.mu.Unlock()
	resp, err := p.up.WriteBatch(ctx, connect.NewRequest(req.Msg))
	if err != nil {
		return nil, err
	}
	return connect.NewResponse(resp.Msg), nil
}

func (p *proxyStore) GetSidecarCursors(ctx context.Context, req *connect.Request[storev1.GetSidecarCursorsRequest]) (*connect.Response[storev1.GetSidecarCursorsResponse], error) {
	resp, err := p.up.GetSidecarCursors(ctx, connect.NewRequest(req.Msg))
	if err != nil {
		return nil, err
	}
	return connect.NewResponse(resp.Msg), nil
}

func (p *proxyStore) unexpected(verb string) error {
	return connect.NewError(connect.CodeUnimplemented,
		fmt.Errorf("the sidecar called %s, which its two-verb store contract forbids", verb))
}

func (p *proxyStore) OpenAgentSession(context.Context, *connect.Request[storev1.OpenAgentSessionRequest]) (*connect.Response[storev1.OpenAgentSessionResponse], error) {
	return nil, p.unexpected("OpenAgentSession")
}

func (p *proxyStore) WatchAgentSession(context.Context, *connect.Request[storev1.WatchAgentSessionRequest], *connect.ServerStream[storev1.WatchAgentSessionResponse]) error {
	return p.unexpected("WatchAgentSession")
}

func (p *proxyStore) ReadAgentPage(context.Context, *connect.Request[storev1.ReadAgentPageRequest]) (*connect.Response[storev1.ReadAgentPageResponse], error) {
	return nil, p.unexpected("ReadAgentPage")
}

func (p *proxyStore) WatchBashRun(context.Context, *connect.Request[storev1.WatchBashRunRequest], *connect.ServerStream[storev1.WatchBashRunResponse]) error {
	return p.unexpected("WatchBashRun")
}

func (p *proxyStore) GetWorkflow(context.Context, *connect.Request[storev1.GetWorkflowRequest]) (*connect.Response[storev1.GetWorkflowResponse], error) {
	return nil, p.unexpected("GetWorkflow")
}

func (p *proxyStore) GetLiveWork(context.Context, *connect.Request[storev1.GetLiveWorkRequest]) (*connect.Response[storev1.GetLiveWorkResponse], error) {
	return nil, p.unexpected("GetLiveWork")
}

// Batches answers every batch the sidecar wrote, in write order.
func (p *proxyStore) Batches() []*storev1.WriteBatchRequest {
	p.mu.Lock()
	defer p.mu.Unlock()
	return append([]*storev1.WriteBatchRequest(nil), p.batches...)
}

// mockIngest is one generated tree, ingested.
type mockIngest struct {
	Tree    *mockTree
	Store   *realStore
	Proxy   *proxyStore
	Sidecar *sidecarProc
}

// Entries answers every StoreEntry the sidecar wrote for this tree, in write
// order — the wire view the residue assertions need.
func (in *mockIngest) Entries() []*storev1.StoreEntry {
	return entriesOf(in.Proxy.Batches())
}

// ingestMock starts the real store and the real sidecar over a generated tree
// and waits until every discovered file's cursor has reached its end — the
// signal that ingestion is COMPLETE, so an assertion of "zero residue" is a
// statement about the whole tree and not about however much had landed.
func ingestMock(t *testing.T, tree *mockTree) *mockIngest {
	t.Helper()
	store := startRealStore(t)
	proxy := startProxyStore(t, store.Socket)
	opts := sidecarOptions{
		StoreSocket:        proxy.Socket,
		ConfigRoots:        []string{tree.ConfigRoot},
		SpoolRoot:          tree.SpoolRoot,
		LogPath:            filepath.Join(t.TempDir(), "sidecar.log"),
		PollInterval:       50 * time.Millisecond,
		RescanEvery:        200 * time.Millisecond,
		UnownedSpoolWindow: 200 * time.Millisecond,
	}
	proc := startSidecar(t, opts)
	in := &mockIngest{Tree: tree, Store: store, Proxy: proxy, Sidecar: proc}
	in.awaitDrained(t)
	return in
}

// awaitDrained blocks until the store's cursor for every generated file names
// at least that file's size. The cursor is the sidecar's OWN statement of what
// it has committed, so it is the only honest completion signal available.
func (in *mockIngest) awaitDrained(t *testing.T) {
	t.Helper()
	ctx, cancel := testContext(t)
	defer cancel()
	var files []string
	files = append(files, in.Tree.Transcripts...)
	files = append(files, in.Tree.Subagents...)
	files = append(files, in.Tree.Spools...)
	for _, path := range files {
		info, err := os.Stat(path)
		if err != nil {
			t.Fatalf("stat generated file %s: %v", path, err)
		}
		if info.Size() == 0 {
			continue
		}
		awaitCursorAtLeast(ctx, t, in.Store.Client, resolved(path), info.Size())
	}
}

// Entries answers every StoreEntry the store now holds for one agent's book,
// read back through the store's own read verb.
func (in *mockIngest) BookLines(t *testing.T, agent string) []*storev1.StoreLineAt {
	t.Helper()
	ctx, cancel := testContext(t)
	defer cancel()
	return bookLines(ctx, t, in.Store.Client, agent, 500)
}

// mockLogTail answers the last few records of the mocked vendor's own log —
// the evidence a drive failure needs, quoted into the failure rather than left
// in a file the reader has to go find.
func mockLogTail(path string) string {
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Sprintf("(the mocked vendor's log at %s could not be read: %v)", path, err)
	}
	lines := strings.Split(strings.TrimRight(string(raw), "\n"), "\n")
	if len(lines) > 12 {
		lines = lines[len(lines)-12:]
	}
	return strings.Join(lines, "\n")
}
