// mock_helpers_test.go — FIXTURES GENERATED BY THE REAL MOCKED VENDOR.
//
// Every other file in this package builds its vendor tree by hand, line by
// line, from testdata/corpus. This file does something different and stronger:
// it RUNS the shim's own `--fake` mocked vendor (agent-shim/claude/shim, built
// from source once per test binary) and lets IT write the transcripts, the
// subagent transcripts and metas, and the task spools. Nothing here copies a
// vendor file; the mock is the only author, exactly as it is in production.
//
// That is the whole point of the exercise: the sidecar's converter is then
// facing the SAME bytes the shim's own scenario suite faces, so a disagreement
// between the two planes shows up as a failing subject here rather than as a
// silent divergence in the field.
//
// The composition per scenario:
//
//  1. a THROWAWAY real store for the SHIM's stream-plane writes — the shim is a
//     store producer too, and its rows must never contaminate what this suite
//     asserts about the sidecar's file-plane rows. See mockVendorStore below.
//  2. `node <shim>/dist/main.js --listen <uds> --store-socket <throwaway>
//     --log-fd 3 --fake`, cwd = a private workspace, CLAUDE_CONFIG_DIR and
//     AGENT_REPL_FAKE_SPOOL_ROOT pointed at private trees.
//  3. shim.v1 over that socket: StartSession{fresh}, StartTurn{the `!name`
//     prompt}, wait on WatchAgent for the turn's terminal, KillSession{force}.
//  4. the REAL store and the REAL sidecar (the ordinary harness) over the tree
//     the mock just wrote.
//
// SYNCHRONIZATION IS ALWAYS A REAL SIGNAL, as everywhere else in this package:
// a WatchAgent frame, a process exit, a bounded ticker-driven re-read of a
// durable surface. There is no time.Sleep here either.
package integration

import (
	"context"
	crand "crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"math/rand"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"testing"
	"time"

	"connectrpc.com/connect"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
	"google.golang.org/protobuf/proto"

	conversationv1 "agentrepl/proto/conversation/v1"
	shimv1 "agentrepl/proto/shim/v1"
	"agentrepl/proto/shim/v1/shimv1connect"
	storev1 "agentrepl/proto/store/v1"
	"agentrepl/proto/store/v1/storev1connect"
	"agentrepl/shim-claude-sidecar/internal/testclose"
)

// ---------------------------------------------------------------------------
// Building the mocked vendor.
// ---------------------------------------------------------------------------

// standDownGrace bounds how long a generated scenario waits for the mocked
// vendor to leave after SIGTERM before killing it. 3s: the mock writes every
// vendor file synchronously and exits promptly on SIGTERM in every observed
// run; the extra margin over shim-store's comparable 2s shutdown bound
// accounts for this being a real node process rather than a compiled binary.
const standDownGrace = 3 * time.Second

var (
	mockShimOnce sync.Once
	mockShimMain string
	mockShimErr  error
)

// ---------------------------------------------------------------------------
// The bound on how many mocked-vendor drives run at once.
// ---------------------------------------------------------------------------

// ONE SCENARIO IS FOUR REAL PROCESSES: a throwaway shim-store for the shim's own
// stream plane, the node shim itself, a second shim-store for the file plane,
// and the sidecar. The scenario table has 133 rows, and every subject in this
// package now runs in parallel — so without a bound the table would land 133
// node processes and 266 stores on the machine at once, which is not a faster
// suite, it is a thrashed one.
//
// THE BOUND IS STRUCTURAL, NOT AN INVOCATION FLAG. `-parallel` governs how many
// test functions Go lets run, and a suite whose safety depended on the caller
// passing the right number would be unsafe under the default. This semaphore
// holds regardless of how the suite is invoked; `-parallel` only decides how
// much of the REST of the package overlaps with it.
//
// The width is half the machine's usable parallelism, floored at 2 and capped
// at 8: each slot is ~4 processes, so 8 slots is ~32 processes, and beyond that
// the drives contend for CPU with the sidecars whose polling they are waiting
// on.
var mockDriveSlots = make(chan struct{}, mockDriveConcurrency())

func mockDriveConcurrency() int {
	n := runtime.GOMAXPROCS(0) / 2
	if n < 2 {
		n = 2
	}
	if n > 8 {
		n = 8
	}
	return n
}

// takeMockDriveSlot blocks until this scenario may run, and gives the slot back
// when the test (and every cleanup it registered) is done.
func takeMockDriveSlot(t *testing.T) {
	t.Helper()
	mockDriveSlots <- struct{}{}
	t.Cleanup(func() { <-mockDriveSlots })
}

// mockShimDir is the shim package's root — READ-ONLY to this suite. Nothing
// here ever writes under it except the `npm ci` / `npm run build` the shim's
// own AGENTS.md documents.
func mockShimDir() string {
	return filepath.Join(repo.agentShimDir, "claude", "shim")
}

// mockShimEntry builds the shim once per test binary and answers the bundle's
// path. A machine without node or npm SKIPS the whole mock package loudly: the
// mocked vendor is a Node program, and pretending to test it without one would
// be a green run that proved nothing.
func mockShimEntry(t *testing.T) string {
	t.Helper()
	for _, tool := range []string{"node", "npm"} {
		if _, err := exec.LookPath(tool); err != nil {
			t.Skipf("SKIPPING the mocked-vendor subjects: %q is not on PATH, and the mock IS a Node program — "+
				"these fixtures are generated by running it, never by copying files (%v)", tool, err)
		}
	}
	mockShimOnce.Do(func() { mockShimMain, mockShimErr = buildMockShim() })
	if mockShimErr != nil {
		t.Fatalf("the mocked vendor does not build, so no fixture can be generated: %v", mockShimErr)
	}
	return mockShimMain
}

func buildMockShim() (string, error) {
	dir := mockShimDir()
	if _, err := os.Stat(filepath.Join(dir, "node_modules")); errors.Is(err, fs.ErrNotExist) {
		if out, err := runIn(dir, "npm", "ci", "--no-audit", "--no-fund"); err != nil {
			return "", fmt.Errorf("npm ci in %s: %v\n%s", dir, err, out)
		}
	} else if err != nil {
		return "", fmt.Errorf("stat %s/node_modules: %w", dir, err)
	}
	if out, err := runIn(dir, "npm", "run", "build"); err != nil {
		return "", fmt.Errorf("npm run build in %s: %v\n%s", dir, err, out)
	}
	entry := filepath.Join(dir, "dist", "main.js")
	if _, err := os.Stat(entry); err != nil {
		return "", fmt.Errorf("the build produced no bundle at %s: %w", entry, err)
	}
	return entry, nil
}

func runIn(dir, name string, args ...string) (string, error) {
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	return string(out), err
}

// ---------------------------------------------------------------------------
// The ONE store the mocked vendor's own stream-plane writes go to.
// ---------------------------------------------------------------------------

// WHY THIS FIXTURE IS SHARED AND THE OTHERS ARE NOT.
//
// A scenario starts four real processes. Three of them are READ BACK by that
// scenario — the sidecar under test, the store it writes to, and the proxy that
// records the wire — so each must be private or one scenario's records would
// answer another's assertions. This fourth one is read back by NOBODY: it
// exists solely so the shim's stream-plane rows have somewhere to go instead of
// contaminating the store this suite asserts on.
//
// A store nobody reads cannot leak one scenario's records into another's
// assertions, so booting 133 of them was 133 process boots bought for nothing.
// One serves the whole test binary and is stood down in runSuite.
//
// Its lifetime is the TEST BINARY's, not a subject's, so it is built without a
// *testing.T: a t.Cleanup would stop it after whichever subject happened to
// need it first.
var (
	vendorStoreOnce   sync.Once
	vendorStoreSocket string
	vendorStoreStop   func()
	vendorStoreErr    error
)

// sharedVendorStoreSocket answers the shared store's socket, starting it on
// first use. A machine whose store does not build or start fails exactly the
// subjects that compose the two systems, and says why.
func sharedVendorStoreSocket(t *testing.T) string {
	t.Helper()
	vendorStoreOnce.Do(func() {
		vendorStoreSocket, vendorStoreStop, vendorStoreErr = startVendorStore()
	})
	if vendorStoreErr != nil {
		t.Fatalf("the mocked vendor needs a store for its own stream-plane writes, and it would not start: %v", vendorStoreErr)
	}
	return vendorStoreSocket
}

// stopSharedVendorStore stands the store down if it was ever started. runSuite
// calls it; nothing else may.
func stopSharedVendorStore() {
	if vendorStoreStop != nil {
		vendorStoreStop()
	}
}

func startVendorStore() (string, func(), error) {
	bin, err := storeBinaryPath()
	if err != nil {
		return "", nil, fmt.Errorf("building the store: %w", err)
	}
	dir, err := os.MkdirTemp("", "ar-vendor-store-")
	if err != nil {
		return "", nil, fmt.Errorf("temp dir: %w", err)
	}
	suffix := make([]byte, 4)
	if _, err := crand.Read(suffix); err != nil {
		return "", nil, errors.Join(fmt.Errorf("random socket suffix: %w", err), os.RemoveAll(dir))
	}
	socket := filepath.Join(os.TempDir(), "ar-vendorstore-"+hex.EncodeToString(suffix)+".sock")
	logPath := filepath.Join(dir, "store.log")
	cmd := exec.Command(bin, "--socket", socket, "--db", filepath.Join(dir, "store.db"), "--log", logPath)
	cmd.Env = append(os.Environ(),
		"AGENT_REPL_STORE_SOCKET="+socket,
		"AGENT_REPL_FORBID_VENDOR_CALLS=1",
		// A private lock dir keeps the boot's build-report write
		// (agentrepl/logging/buildreport) out of the owner's real
		// ~/.cache/agent-repl/run.
		"AGENT_REPL_LOCK_DIR="+filepath.Join(dir, "lock"),
	)
	// Its output is kept, not printed: no subject owns it, and interleaving it
	// with 133 scenarios' output would be noise. A failure to START is reported
	// through the error above, and the log file survives in the temp dir until
	// the stand-down removes it.
	var sink childOutput
	cmd.Stdout = &sink
	cmd.Stderr = &sink
	if err := cmd.Start(); err != nil {
		return "", nil, errors.Join(fmt.Errorf("start: %w", err), os.RemoveAll(dir))
	}
	done := make(chan error, 1)
	go func() { done <- cmd.Wait() }()
	stop := func() {
		if cmd.Process != nil {
			_ = cmd.Process.Signal(syscall.SIGTERM)
		}
		select {
		case <-done:
		case <-time.After(waitBudget):
			if cmd.Process != nil {
				_ = cmd.Process.Kill()
			}
			<-done
		}
		// Nothing here has a *testing.T: this stop runs once, at process
		// teardown (runSuite's defer), for the mocked-vendor suite's ONE
		// shared throwaway store — so a teardown failure is stated loudly to
		// stderr rather than checked against a test that no longer exists.
		if err := os.Remove(socket); err != nil && !os.IsNotExist(err) {
			fmt.Fprintf(os.Stderr, "integration: removing vendor store socket %s: %v\n", socket, err)
		}
		if err := os.RemoveAll(dir); err != nil {
			fmt.Fprintf(os.Stderr, "integration: removing vendor store dir %s: %v\n", dir, err)
		}
	}

	// READY IS AN ANSWERED RPC, never a duration.
	ctx, cancel := context.WithTimeout(context.Background(), waitBudget)
	defer cancel()
	client := storeClient(socket)
	tick := time.NewTicker(pollTick)
	defer tick.Stop()
	for {
		if _, err := client.GetSidecarCursors(ctx, connect.NewRequest(&storev1.GetSidecarCursorsRequest{})); err == nil {
			return socket, stop, nil
		}
		select {
		case <-ctx.Done():
			stop()
			return "", nil, fmt.Errorf("it never answered GetSidecarCursors within %s; its output was:\n%s", waitBudget, sink.buf.String())
		case <-tick.C:
		}
	}
}

// ---------------------------------------------------------------------------
// One generated vendor tree.
// ---------------------------------------------------------------------------

// mockTree is what one scenario run left on disk, plus the roots the sidecar
// must be pointed at to read it.
//
// SESSION IDS ARE DISCOVERED, NEVER COMPUTED. The cwd slug is a lossy mapping
// and the mock resolves its own cwd (macOS's /var → /private/var), so the tree
// is enumerated after the run rather than predicted before it. A rotation
// scenario therefore reports BOTH identities without the harness knowing in
// advance that it rotated.
type mockTree struct {
	ConfigRoot string // the sidecar's --config-roots entry (CLAUDE_CONFIG_DIR)
	SpoolRoot  string // the sidecar's --spool-root (parent of claude-<uid>)
	FakeSpool  string // what the mock was given: <SpoolRoot>/claude-<uid>
	Cwd        string // the workspace the mock ran in
	LogPath    string // the shim's own log (fd 3), for evidence in failures
	State      string // the shim's AGENT_REPL_STATE_DIR, holding its identity records

	// VendorSessionID is what StartSession reported: the session the turn ran
	// under. After a rotation the LAST transcript is a different id.
	VendorSessionID string

	// Transcripts is every `<session>.jsonl` the mock wrote, sorted by mtime
	// (oldest first). Each basename is a MAIN AGENT ID under R9.
	Transcripts []string

	// Subagents is every `agent-<id>.jsonl` under any session's subagents dir.
	Subagents []string

	// Spools is every `<task>.output` the mock wrote.
	Spools []string
}

// MainAgentIDs answers the R9 main-agent identity of every transcript: the
// FILE's session uuid, never the per-record sessionId.
func (m *mockTree) MainAgentIDs() []string {
	ids := make([]string, 0, len(m.Transcripts))
	for _, p := range m.Transcripts {
		ids = append(ids, strings.TrimSuffix(filepath.Base(p), ".jsonl"))
	}
	return ids
}

// LastMainAgentID is the identity in force when the turn ended — the same as
// VendorSessionID except in a rotation scenario, where the turn's tail belongs
// to the NEW identity.
func (m *mockTree) LastMainAgentID() string {
	ids := m.MainAgentIDs()
	if len(ids) == 0 {
		return ""
	}
	return ids[len(ids)-1]
}

// ---------------------------------------------------------------------------
// Driving one scenario.
// ---------------------------------------------------------------------------

// mockWait says what ends the drive for a scenario.
type mockWait int

const (
	// waitTerminal — the ordinary case: the turn reaches AgentSuccess or
	// AgentFailure on the main agent's WatchAgent stream.
	waitTerminal mockWait = iota
	// waitEntries — a scenario whose turn deliberately NEVER terminates
	// (`!hold`, `!query-eof`, `!query-fail`, the live detached ones). The
	// drive ends when the stream has delivered at least one entry, which is
	// still a real signal and never a duration.
	waitEntries
	// waitAnswer — a scenario that BLOCKS ON THE USER: a permission gate or an
	// AskUserQuestion batch. The drive answers each ask as its start frame
	// arrives (through UpdateAgent, the one verb for speaking to an existing
	// agent) and then goes on waiting for the turn's terminal. Without this the
	// turn parks forever and the mock writes only the records before the gate.
	waitAnswer
	// waitDetach — a scenario that BLOCKS ON a vendor-side backgrounding of
	// foreground work mid-flight. The drive calls
	// DetachForeground on the bash unit as its start frame arrives and then goes
	// on waiting for the turn's terminal.
	//
	// WITHOUT THE DETACH THERE IS NO FIXTURE. The scenario parks on
	// `awaitBackgrounded`, so its tool_result — the ONLY place the vendor states
	// which task the spool belongs to — is never written, and the spool it
	// already opened ages out unclaimed into residue. That is a drive that never
	// performed the user's half of the scenario, not a sidecar defect.
	waitDetach
)

// generateMock runs ONE scenario through the real mocked vendor and answers the
// tree it wrote.
func generateMock(t *testing.T, prompt string, wait mockWait) *mockTree {
	t.Helper()
	entry := mockShimEntry(t)
	// EVERY DRIVE IS BOUNDED, not just the table's. The bound lives here rather
	// than at the call sites so a new mocked-vendor subject cannot be added
	// outside it, and so the count the semaphore enforces is the count of
	// drives actually running.
	takeMockDriveSlot(t)

	base := t.TempDir()
	tree := &mockTree{
		ConfigRoot: filepath.Join(base, "config"),
		SpoolRoot:  filepath.Join(base, "spool"),
		Cwd:        filepath.Join(base, "work"),
		LogPath:    filepath.Join(base, "shim.log"),
		State:      filepath.Join(base, "state"),
	}
	tree.FakeSpool = filepath.Join(tree.SpoolRoot, "claude-"+spoolUID)
	for _, d := range []string{tree.ConfigRoot, tree.FakeSpool, tree.Cwd, filepath.Join(base, "state"), filepath.Join(base, "lock")} {
		mustMkdirAll(t, d)
	}
	// The mock resolves its own cwd; comparing an unresolved one against a
	// discovered path would fail on macOS, where /var is a symlink.
	tree.Cwd = resolved(tree.Cwd)

	// The shim's OWN store: a throwaway, and SHARED by every scenario. The shim
	// writes the stream plane, and mixing those rows into the store this suite
	// reads back would mean a sidecar assertion could pass on a row the SHIM
	// wrote — which is why it is a separate store, and why nobody reads it,
	// which is in turn why one serves them all. See sharedVendorStoreSocket.
	vendorStoreSocket := sharedVendorStoreSocket(t)

	logFile, err := os.Create(tree.LogPath)
	if err != nil {
		t.Fatalf("create the mocked vendor's log: %v", err)
	}
	t.Cleanup(func() { _ = logFile.Close() })

	socket := shimListenSocketPath(t)
	cmd := exec.Command("node", entry,
		"--listen", socket,
		"--store-socket", vendorStoreSocket,
		"--log-fd", "3",
		"--fake",
	)
	cmd.Dir = tree.Cwd
	cmd.ExtraFiles = []*os.File{logFile} // becomes fd 3 in the child
	cmd.Env = append(os.Environ(),
		"CLAUDE_CONFIG_DIR="+tree.ConfigRoot,
		"AGENT_REPL_FAKE_SPOOL_ROOT="+tree.FakeSpool,
		"AGENT_REPL_STATE_DIR="+tree.State,
		"AGENT_REPL_LOCK_DIR="+filepath.Join(base, "lock"),
		// The shim spawns this for each kernel claim; without it the mocked
		// vendor refuses every session and generates no fixture at all.
		"AGENT_REPL_SHIM_LOCK_BIN="+lockBinary(t),
		"AGENT_REPL_STORE_SOCKET="+vendorStoreSocket,
		"AGENT_REPL_OWNED=1",
		"SHIM_BUILD_SHA=test",
		"AGENT_REPL_FORBID_VENDOR_CALLS=1",
	)
	captured := captureChild(t, "the mocked vendor (log: "+tree.LogPath+")")
	cmd.Stdout = captured
	cmd.Stderr = captured
	if err := cmd.Start(); err != nil {
		t.Fatalf("spawn the mocked vendor: %v", err)
	}
	done := make(chan error, 1)
	go func() { done <- cmd.Wait() }()
	stopped := false
	stop := func() {
		if stopped {
			return
		}
		stopped = true
		if cmd.Process != nil {
			_ = cmd.Process.Kill()
		}
		<-done
	}
	t.Cleanup(stop)

	ctx, cancel := testContext(t)
	defer cancel()
	awaitSocket(ctx, t, socket, tree)

	httpClient := udsHTTPClient(socket)
	client := shimv1connect.NewShimClient(httpClient, "http://shim")
	agent := startMockSession(ctx, t, client, tree)
	tree.VendorSessionID = agent.vendorSessionID
	driveMockTurn(ctx, t, client, prompt, agent.agentID, wait, tree)

	// KillSession{force} is the authorized stand-down: it interrupts whatever is
	// still live and lets the mock finish writing its files. It does NOT end the
	// process — the shim outlives its daemon by design, and SIGTERM is its one
	// authorized shutdown — so the stand-down is followed by SIGTERM, and the
	// process EXIT is the signal that the tree is complete.
	// Every connection this drive opened is dropped BEFORE the stand-down: a
	// server with a live socket does not stop serving, so a lingering pooled
	// connection would turn the stand-down into a hang that looks like a mock
	// defect and is not one.
	httpClient.CloseIdleConnections()
	//
	// SIGTERM IS THE STAND-DOWN, not a bare kill: the shim's contract makes
	// SIGTERM take the `KillSession{force:true}` path internally and then exit 0.
	// Calling the rpc first and signalling second would be the same stand-down
	// twice, and the rpc does not return while the process is still serving the
	// streams this drive opened.
	if cmd.Process != nil {
		_ = cmd.Process.Signal(syscall.SIGTERM)
	}
	select {
	case <-done:
		stopped = true
	case <-time.After(standDownGrace):
		// The stand-down is bounded, not awaited forever: the mock writes every
		// vendor file synchronously (appendFileSync), so the tree is already
		// complete by the time the turn's terminal was observed, and a mock that
		// will not leave must not hold the whole suite. The kill is reported so a
		// stand-down regression is visible rather than absorbed.
		t.Logf("the mocked vendor did not leave within %s of SIGTERM; killing it. Its log tail:\n%s",
			standDownGrace, mockLogTail(tree.LogPath))
		if cmd.Process != nil {
			_ = cmd.Process.Kill()
		}
		<-done
		stopped = true
	}

	enumerateMockTree(t, tree)
	return tree
}

// awaitSocket waits until the mocked vendor is ACCEPTING, not until its socket
// file exists.
//
// A unix socket's inode is created by bind() and only becomes connectable at
// listen(), so a stat that succeeds in that window is followed by a dial that
// is REFUSED. The readiness signal is therefore an accepted connection, which
// cannot be observed before the listener exists.
func awaitSocket(ctx context.Context, t *testing.T, socket string, tree *mockTree) {
	t.Helper()
	tick := time.NewTicker(pollTick)
	defer tick.Stop()
	for {
		if conn, err := net.Dial("unix", socket); err == nil {
			_ = conn.Close()
			return
		}
		select {
		case <-ctx.Done():
			t.Fatalf("the mocked vendor never bound %s; its log is at %s", socket, tree.LogPath)
		case <-tick.C:
		}
	}
}

type mockSession struct {
	vendorSessionID string
	agentID         *conversationv1.AgentId
}

func startMockSession(ctx context.Context, t *testing.T, c shimv1connect.ShimClient, tree *mockTree) mockSession {
	t.Helper()
	resp, err := c.StartSession(ctx, connect.NewRequest(&shimv1.StartSessionRequest{
		Source: &shimv1.StartSessionRequest_Fresh{Fresh: &shimv1.StartSessionFresh{
			// Both fields are non-optional, so both are set: the validation
			// invariant makes an unset one illegal, not defaulted.
			Model: &conversationv1.AgentModel{Name: "claude-opus-5"},
			PermissionMode: &conversationv1.AgentPermissionMode{
				Mode: &conversationv1.AgentPermissionMode_Bypass{Bypass: &conversationv1.AgentPermissionModeBypass{}},
			},
		}},
	}))
	if err != nil {
		t.Fatalf("StartSession on the mocked vendor: %v (log: %s)", err, tree.LogPath)
	}
	success := resp.Msg.GetSuccess()
	if success == nil {
		t.Fatalf("StartSession was refused: %v (log: %s)", resp.Msg.GetFailure(), tree.LogPath)
	}
	return mockSession{vendorSessionID: success.GetSession().GetVendorSessionId()}
}

func driveMockTurn(
	ctx context.Context,
	t *testing.T,
	c shimv1connect.ShimClient,
	prompt string,
	_ *conversationv1.AgentId,
	wait mockWait,
	tree *mockTree,
) {
	t.Helper()
	turnID := &conversationv1.TurnId{Value: "turn-" + randomHex()}
	resp, err := c.StartTurn(ctx, connect.NewRequest(&shimv1.StartTurnRequest{
		Turn: turnID,
		Said: &conversationv1.UserSaid{Content: &conversationv1.UserContent{
			Blocks: []*conversationv1.UserContentBlock{{
				Block: &conversationv1.UserContentBlock_Text{
					Text: &conversationv1.TextBlock{Text: prompt},
				},
			}},
		}},
		Origin: conversationv1.PromptOrigin_PROMPT_ORIGIN_USER_SENT,
	}))
	if err != nil {
		t.Fatalf("StartTurn(%q): %v (log: %s)", prompt, err, tree.LogPath)
	}
	success := resp.Msg.GetSuccess()
	if success == nil {
		t.Fatalf("StartTurn(%q) was refused: %v (log: %s)", prompt, resp.Msg.GetFailure(), tree.LogPath)
	}
	awaitMockTurnEnd(ctx, t, c, success.GetPrompt().GetAgent(), wait, prompt, tree)
}

// awaitMockTurnEnd tails the main agent and returns on the turn's terminal —
// or, for a scenario that deliberately never terminates, on the first entry.
func awaitMockTurnEnd(
	ctx context.Context,
	t *testing.T,
	c shimv1connect.ShimClient,
	target *conversationv1.AgentId,
	wait mockWait,
	prompt string,
	tree *mockTree,
) {
	t.Helper()
	// WatchAgent is a STANDING stream: it never concludes on its own, because
	// the terminal fact rides the entries and the caller closes when it stops
	// caring. Closing it therefore means CANCELLING it — a plain Close would
	// wait for a server that has no reason to hang up, which reads as a hang
	// and is really just the contract.
	watchCtx, closeWatch := context.WithCancel(ctx)
	defer closeWatch()
	stream, err := c.WatchAgent(watchCtx, connect.NewRequest(&shimv1.WatchAgentRequest{
		Target: target,
	}))
	if err != nil {
		t.Fatalf("WatchAgent for %q: %v (log: %s)", prompt, err, tree.LogPath)
	}

	seen := 0
	answered := map[string]bool{}
	for stream.Receive() {
		var entries []*conversationv1.HistoryEntry
		switch frame := stream.Msg().GetFrame().(type) {
		case *shimv1.WatchAgentResponse_Page:
			for _, e := range frame.Page.GetEntries() {
				entries = append(entries, e.GetEntry())
			}
		case *shimv1.WatchAgentResponse_Entry:
			entries = append(entries, stream.Msg().GetEntry().GetEntry())
		}
		for _, entry := range entries {
			seen++
			if isMockTerminal(entry) && wait != waitEntries {
				return
			}
			if wait == waitAnswer {
				answerOpenAsk(ctx, t, c, target, entry, prompt, answered, tree)
			}
			if wait == waitDetach {
				detachOpenBash(ctx, t, c, entry, prompt, answered, tree)
			}
		}
		if wait == waitEntries && seen > 0 {
			return
		}
	}
	if err := stream.Err(); err != nil && ctx.Err() == nil {
		t.Fatalf("WatchAgent for %q ended: %v (log: %s)", prompt, err, tree.LogPath)
	}
	if wait != waitEntries {
		t.Fatalf("the turn for %q never reached a terminal frame (log: %s)", prompt, tree.LogPath)
	}
}

// answerOpenAsk decides one open permission gate or answers one open question
// batch, so a scenario that blocks on the user can reach its terminal.
//
// The DECISION follows the scenario's own name, because the scenario table
// declares what the user did: a `!perm-deny-*` row is the row where the user
// denies, and answering it with an allow would generate the wrong fixture.
// Every other gate is allowed once, and every question is answered with the
// FIRST option each of its questions offered.
func answerOpenAsk(
	ctx context.Context,
	t *testing.T,
	c shimv1connect.ShimClient,
	target *conversationv1.AgentId,
	entry *conversationv1.HistoryEntry,
	prompt string,
	answered map[string]bool,
	tree *mockTree,
) {
	t.Helper()
	update := entry.GetAgentFrame().GetUpdate()
	var input *conversationv1.AgentInput
	switch {
	case update.GetPermission().GetStart() != nil:
		ask := update.GetPermission().GetId()
		if answered["permission:"+ask.GetValue()] {
			return
		}
		answered["permission:"+ask.GetValue()] = true
		decision := &conversationv1.AgentPermissionDecision{Ask: ask}
		if strings.HasPrefix(prompt, "!perm-deny") {
			decision.Decision = &conversationv1.AgentPermissionDecision_Denied{
				Denied: &conversationv1.AgentPermissionDeniedByUser{Message: "the user declined this call"},
			}
		} else {
			decision.Decision = &conversationv1.AgentPermissionDecision_Allowed{
				Allowed: &conversationv1.AgentPermissionAllowed{
					Scope: &conversationv1.AgentPermissionAllowed_Once{Once: &conversationv1.AgentPermissionAllowedOnce{}},
				},
			}
		}
		input = &conversationv1.AgentInput{Input: &conversationv1.AgentInput_Answer{
			Answer: &conversationv1.AgentAnswer{
				Answer: &conversationv1.AgentAnswer_PermissionDecision{PermissionDecision: decision},
			},
		}}
	case update.GetQuestion().GetStart() != nil:
		ask := update.GetQuestion().GetId()
		if answered["question:"+ask.GetValue()] {
			return
		}
		answered["question:"+ask.GetValue()] = true
		answers := &conversationv1.AgentQuestionAnswers{}
		for _, asked := range update.GetQuestion().GetStart().GetBatch().GetQuestions() {
			selection := &conversationv1.AgentQuestionSelection{Question: asked.GetQuestion()}
			options := asked.GetSingleSelect().GetOptions()
			if options == nil {
				options = asked.GetMultiSelect().GetOptions()
			}
			if len(options) == 0 {
				// No option to echo: the ask's own free-text escape is the only
				// answer available, and it is always offered.
				selection.FreeText = &conversationv1.AgentQuestionFreeText{Text: "no options were offered"}
			} else {
				selection.Chosen = []*conversationv1.AgentQuestionChoice{{Label: options[0].GetLabel()}}
			}
			answers.Answers = append(answers.Answers, selection)
		}
		input = &conversationv1.AgentInput{Input: &conversationv1.AgentInput_Answer{
			Answer: &conversationv1.AgentAnswer{
				Answer: &conversationv1.AgentAnswer_QuestionAnswer{
					QuestionAnswer: &conversationv1.AgentQuestionAnswer{Ask: ask, Answers: answers},
				},
			},
		}}
	default:
		return
	}
	resp, err := c.UpdateAgent(ctx, connect.NewRequest(&shimv1.UpdateAgentRequest{Target: target, Input: input}))
	if err != nil {
		t.Fatalf("UpdateAgent answering the ask %q blocked on: %v (log: %s)", prompt, err, tree.LogPath)
	}
	if resp.Msg.GetSuccess() == nil {
		t.Fatalf("the mocked vendor REFUSED the answer to %q: %v (log: %s)",
			prompt, resp.Msg.GetFailure(), tree.LogPath)
	}
}

// detachOpenBash confirms one announced foreground bash unit's
// vendor-side backgrounding, so a scenario parked on the detachment can
// reach its terminal.
//
// THE UNIT IS THE BASH'S OWN ACTIVITY ID, which is the vendor tool_use id the
// mock's `backgroundTasks(toolUseId)` answers on — the same identity
// DetachForeground's request field declares.
func detachOpenBash(
	ctx context.Context,
	t *testing.T,
	c shimv1connect.ShimClient,
	entry *conversationv1.HistoryEntry,
	prompt string,
	detached map[string]bool,
	tree *mockTree,
) {
	t.Helper()
	activity := entry.GetAgentFrame().GetUpdate().GetActivity()
	if activity.GetBash().GetStart() == nil {
		return
	}
	unit := activity.GetActivityId()
	if unit.GetValue() == "" || detached["detach:"+unit.GetValue()] {
		return
	}
	detached["detach:"+unit.GetValue()] = true
	resp, err := c.DetachForeground(ctx, connect.NewRequest(&shimv1.DetachForegroundRequest{Unit: unit}))
	if err != nil {
		t.Fatalf("DetachForeground on the bash unit of %q: %v (log: %s)", prompt, err, tree.LogPath)
	}
	if resp.Msg.GetSuccess() == nil {
		t.Fatalf("the mocked vendor REFUSED the DetachForeground on %q: %v (log: %s)",
			prompt, resp.Msg.GetFailure(), tree.LogPath)
	}
}

// isMockTerminal answers whether an entry is a turn terminal — the success or
// failure arm of an AgentFrame, which is exactly what agent.proto declares as
// "the agent ended".
func isMockTerminal(entry *conversationv1.HistoryEntry) bool {
	frame := entry.GetAgentFrame()
	if frame == nil {
		return false
	}
	switch frame.GetResult().(type) {
	case *conversationv1.AgentFrame_Success, *conversationv1.AgentFrame_Failure:
		return true
	default:
		return false
	}
}

func randomHex() string {
	b := make([]byte, 6)
	// A test-local id needs to be unique within one process, not unguessable.
	for i := range b {
		b[i] = byte(rand.Intn(256))
	}
	return hex.EncodeToString(b)
}

// enumerateMockTree walks what the mock wrote. It is the ONLY source of the
// tree's shape: nothing here predicts a path.
func enumerateMockTree(t *testing.T, tree *mockTree) {
	t.Helper()
	type stamped struct {
		path string
		mod  time.Time
	}
	var transcripts []stamped
	projects := filepath.Join(tree.ConfigRoot, "projects")
	err := filepath.WalkDir(projects, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".jsonl") {
			return nil
		}
		info, statErr := d.Info()
		if statErr != nil {
			return statErr
		}
		if filepath.Base(filepath.Dir(path)) == "subagents" {
			tree.Subagents = append(tree.Subagents, path)
			return nil
		}
		transcripts = append(transcripts, stamped{path: path, mod: info.ModTime()})
		return nil
	})
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("walking the generated transcript tree %s: %v", projects, err)
	}
	sort.Slice(transcripts, func(i, j int) bool { return transcripts[i].mod.Before(transcripts[j].mod) })
	for _, s := range transcripts {
		tree.Transcripts = append(tree.Transcripts, s.path)
	}
	sort.Strings(tree.Subagents)

	err = filepath.WalkDir(tree.SpoolRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(path, ".output") {
			tree.Spools = append(tree.Spools, path)
		}
		return nil
	})
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("walking the generated spool tree %s: %v", tree.SpoolRoot, err)
	}
	sort.Strings(tree.Spools)
}

// ---------------------------------------------------------------------------
// Ingesting a generated tree with the REAL store and the REAL sidecar.
// ---------------------------------------------------------------------------

// proxyStore is a RECORDING PASS-THROUGH in front of the real store.
//
// Why it exists: the residue arms (`unparsed`, `unknown`, `vendor_specific`)
// are DURABLE but have no read verb — store/v1 serves pages, bash runs, live
// work and cursors, and nothing enumerates unserved items. A subject that must
// assert "this scenario produced ZERO unparsed residue" therefore has to read
// the WIRE. The proxy records every `WriteBatch` and forwards it verbatim, so
// the same run is both fully visible on the wire AND fully durable in the real
// store, and the book/bash assertions still read back through the store's own
// verbs.
//
// It implements the verbs the sidecar's contract allows it to call and
// nothing else: a sidecar reaching any other verb is a contract violation, and
// an `unimplemented` answer states that instead of hiding it.
type proxyStore struct {
	t      *testing.T
	Socket string
	up     storev1connect.ShimStoreClient

	mu      sync.Mutex
	batches []*storev1.WriteBatchRequest

	// gate, when armed, WITHHOLDS the answer to the first batch that matches
	// it — the same interlock the fake store offers, for the subjects that
	// need the REAL store's behavior behind it. See writeGate.
	gate *writeGate

	srv     *http.Server
	ln      net.Listener
	done    chan struct{}
	stopped bool
}

var _ storev1connect.ShimStoreHandler = (*proxyStore)(nil)

// gateOnBatch arms the proxy's one-shot write gate, released at cleanup
// whatever the subject does so a failure can never leave a producer wedged in
// a write.
func (p *proxyStore) gateOnBatch(t *testing.T, match func(*storev1.WriteBatchRequest) bool) *writeGate {
	t.Helper()
	g := &writeGate{match: match, reached: make(chan struct{}), released: make(chan struct{})}
	p.mu.Lock()
	p.gate = g
	p.mu.Unlock()
	t.Cleanup(g.release)
	return g
}

func startProxyStore(t *testing.T, upstream string) *proxyStore {
	t.Helper()
	socket := shortSocketPath(t, "proxy")
	p := &proxyStore{t: t, Socket: socket, up: storeClient(upstream), done: make(chan struct{})}
	mux := http.NewServeMux()
	path, handler := storev1connect.NewShimStoreHandler(p)
	mux.Handle(path, handler)
	ln, err := net.Listen("unix", socket)
	if err != nil {
		t.Fatalf("listen on %s: %v", socket, err)
	}
	p.ln = ln
	p.srv = &http.Server{Handler: h2c.NewHandler(mux, &http2.Server{})}
	go func() {
		defer close(p.done)
		_ = p.srv.Serve(ln)
	}()
	t.Cleanup(p.Stop)
	return p
}

func (p *proxyStore) Stop() {
	p.t.Helper()
	p.mu.Lock()
	if p.stopped {
		p.mu.Unlock()
		return
	}
	p.stopped = true
	p.mu.Unlock()
	ctx, cancel := context.WithTimeout(context.Background(), waitBudget)
	defer cancel()
	_ = p.srv.Shutdown(ctx)
	<-p.done
	testclose.RemoveOrFail(p.t, p.Socket)
}

func (p *proxyStore) WriteBatch(ctx context.Context, req *connect.Request[storev1.WriteBatchRequest]) (*connect.Response[storev1.WriteBatchResponse], error) {
	recorded := proto.Clone(req.Msg).(*storev1.WriteBatchRequest)
	p.mu.Lock()
	p.batches = append(p.batches, recorded)
	gate := p.gate
	p.mu.Unlock()
	resp, err := p.up.WriteBatch(ctx, connect.NewRequest(req.Msg))
	if err != nil {
		return nil, err
	}
	// The upstream store has already COMMITTED the batch and only the answer is
	// withheld, so a subject waiting on the gate reads the same durable state
	// the producer just wrote.
	gate.hold(recorded)
	return connect.NewResponse(resp.Msg), nil
}

func (p *proxyStore) GetSidecarCursors(ctx context.Context, req *connect.Request[storev1.GetSidecarCursorsRequest]) (*connect.Response[storev1.GetSidecarCursorsResponse], error) {
	resp, err := p.up.GetSidecarCursors(ctx, connect.NewRequest(req.Msg))
	if err != nil {
		return nil, err
	}
	return connect.NewResponse(resp.Msg), nil
}

func (p *proxyStore) GetShellRunClaims(ctx context.Context, req *connect.Request[storev1.GetShellRunClaimsRequest]) (*connect.Response[storev1.GetShellRunClaimsResponse], error) {
	resp, err := p.up.GetShellRunClaims(ctx, connect.NewRequest(req.Msg))
	if err != nil {
		return nil, err
	}
	return connect.NewResponse(resp.Msg), nil
}

func (p *proxyStore) GetRunSettlements(ctx context.Context, req *connect.Request[storev1.GetRunSettlementsRequest]) (*connect.Response[storev1.GetRunSettlementsResponse], error) {
	resp, err := p.up.GetRunSettlements(ctx, connect.NewRequest(req.Msg))
	if err != nil {
		return nil, err
	}
	return connect.NewResponse(resp.Msg), nil
}

func (p *proxyStore) unexpected(verb string) error {
	return connect.NewError(connect.CodeUnimplemented,
		fmt.Errorf("the sidecar called %s, which its store contract forbids", verb))
}

func (p *proxyStore) OpenAgentSession(context.Context, *connect.Request[storev1.OpenAgentSessionRequest]) (*connect.Response[storev1.OpenAgentSessionResponse], error) {
	return nil, p.unexpected("OpenAgentSession")
}

func (p *proxyStore) WatchAgentSession(context.Context, *connect.Request[storev1.WatchAgentSessionRequest], *connect.ServerStream[storev1.WatchAgentSessionResponse]) error {
	return p.unexpected("WatchAgentSession")
}

func (p *proxyStore) ReadAgentPage(context.Context, *connect.Request[storev1.ReadAgentPageRequest]) (*connect.Response[storev1.ReadAgentPageResponse], error) {
	return nil, p.unexpected("ReadAgentPage")
}

func (p *proxyStore) WatchBashRun(context.Context, *connect.Request[storev1.WatchBashRunRequest], *connect.ServerStream[storev1.WatchBashRunResponse]) error {
	return p.unexpected("WatchBashRun")
}

func (p *proxyStore) GetWorkflow(context.Context, *connect.Request[storev1.GetWorkflowRequest]) (*connect.Response[storev1.GetWorkflowResponse], error) {
	return nil, p.unexpected("GetWorkflow")
}

func (p *proxyStore) GetLiveWork(context.Context, *connect.Request[storev1.GetLiveWorkRequest]) (*connect.Response[storev1.GetLiveWorkResponse], error) {
	return nil, p.unexpected("GetLiveWork")
}

func (p *proxyStore) GetAgentByVendorTask(context.Context, *connect.Request[storev1.GetAgentByVendorTaskRequest]) (*connect.Response[storev1.GetAgentByVendorTaskResponse], error) {
	return nil, p.unexpected("GetAgentByVendorTask")
}

func (p *proxyStore) ListResidueShapes(context.Context, *connect.Request[storev1.ListResidueShapesRequest]) (*connect.Response[storev1.ListResidueShapesResponse], error) {
	return nil, p.unexpected("ListResidueShapes")
}

// Batches answers every batch the sidecar wrote, in write order.
func (p *proxyStore) Batches() []*storev1.WriteBatchRequest {
	p.mu.Lock()
	defer p.mu.Unlock()
	return append([]*storev1.WriteBatchRequest(nil), p.batches...)
}

// mockIngest is one generated tree, ingested.
type mockIngest struct {
	Tree    *mockTree
	Store   *realStore
	Proxy   *proxyStore
	Sidecar *sidecarProc
}

// Entries answers every StoreEntry the sidecar wrote for this tree, in write
// order — the wire view the residue assertions need.
func (in *mockIngest) Entries() []*storev1.StoreEntry {
	return entriesOf(in.Proxy.Batches())
}

// ingestMock starts the real store and the real sidecar over a generated tree
// and waits until every discovered file's cursor has reached its end — the
// signal that ingestion is COMPLETE, so an assertion of "zero residue" is a
// statement about the whole tree and not about however much had landed.
func ingestMock(t *testing.T, tree *mockTree) *mockIngest {
	t.Helper()
	store := startRealStore(t)
	proxy := startProxyStore(t, store.Socket)
	// THE MOCKED VENDOR'S SHIM IS GONE BY NOW, and a workspace is active only
	// while a shim holds its lock. The subject stands in for that shim over the
	// identity records it left, so its conversation is live for this sidecar.
	newLiveRoot(t, tree.State).holdEveryRecordedWorkspace(t)
	opts := sidecarOptions{
		StateDir:           tree.State,
		StoreSocket:        proxy.Socket,
		ConfigRoots:        []string{tree.ConfigRoot},
		SpoolRoot:          tree.SpoolRoot,
		LogPath:            filepath.Join(t.TempDir(), "sidecar.log"),
		PollInterval:       50 * time.Millisecond,
		RescanEvery:        200 * time.Millisecond,
		UnownedSpoolWindow: 200 * time.Millisecond,
	}
	proc := startSidecar(t, opts)
	in := &mockIngest{Tree: tree, Store: store, Proxy: proxy, Sidecar: proc}
	in.awaitDrained(t)
	return in
}

// awaitDrained blocks until the store's cursor for every generated file names
// at least that file's size. The cursor is the sidecar's OWN statement of what
// it has committed, so it is the only honest completion signal available.
func (in *mockIngest) awaitDrained(t *testing.T) {
	t.Helper()
	ctx, cancel := testContext(t)
	defer cancel()
	var files []string
	files = append(files, in.Tree.Transcripts...)
	files = append(files, in.Tree.Subagents...)
	files = append(files, in.Tree.Spools...)
	for _, path := range files {
		info, err := os.Stat(path)
		if err != nil {
			t.Fatalf("stat generated file %s: %v", path, err)
		}
		if info.Size() == 0 {
			continue
		}
		awaitCursorAtLeast(ctx, t, in.Store.Client, resolved(path), info.Size())
	}
}

// mockLogTail answers the last few records of the mocked vendor's own log —
// the evidence a drive failure needs, quoted into the failure rather than left
// in a file the reader has to go find.
func mockLogTail(path string) string {
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Sprintf("(the mocked vendor's log at %s could not be read: %v)", path, err)
	}
	lines := strings.Split(strings.TrimRight(string(raw), "\n"), "\n")
	if len(lines) > 12 {
		lines = lines[len(lines)-12:]
	}
	return strings.Join(lines, "\n")
}

// ---------------------------------------------------------------------------
// The invariants every generated scenario must satisfy.
// ---------------------------------------------------------------------------

// allowedVendorSpecificPrefixes and allowedVendorSpecificKinds are the residue
// classes the sidecar's AGENTS.md documents ("Withholding classes"). A kind
// outside them is a MODELLING GAP the mock exposed, not a licence to widen the
// list: widening it needs the evidence stated in the report.
var (
	allowedVendorSpecificPrefixes = []string{
		"attachment/",    // context-cut exclusions and the other attachment machinery
		"content_block/", // unmodeled content blocks
		"system/",        // the informational / turn_duration / away_summary … system lines
		"file-history-",  // the file-history pair
		"workflow/",      // workflow journals and spools — KICKED this wave
	}
	allowedVendorSpecificKinds = map[string]bool{
		"mode":                 true,
		"permission-mode":      true,
		"queue-operation":      true,
		"last-prompt":          true,
		"ai-title":             true,
		"pr-link":              true,
		"frame-link":           true,
		"attribution-snapshot": true,
		// A harness-injected user record: the system reminder, and the
		// `<local-command-caveat>` the `identity-rotation-clear` capture shows
		// immediately before a slash command's envelope.
		"user/meta":              true,
		"no_response_requested":  true,
		vendorSpecificUserPrompt: true, // R15: a file-plane user prompt is never a page line
	}
)

// orphanToolResultKind is what a tool_result whose CALL is behind the cursor
// lands on. It is DELIBERATELY NOT a documented withholding class: a withholding
// class is a record we understood and chose not to carry, and this is a settle
// we FAILED to perform — the unit it belonged to stays open in every reader.
//
// The mocked vendor writes each scenario's transcript from the top, so the
// sidecar reads every call before its result and no scenario has any excuse to
// produce one. Allowing the kind made the whole mock suite blind to a join the
// converter had simply stopped performing.
const orphanToolResultKind = "orphan_tool_result"

// requireNoOrphanToolResults: every tool_result the mock writes must settle the
// call it answers.
func requireNoOrphanToolResults(t *testing.T, scenario string, entries []*storev1.StoreEntry) {
	t.Helper()
	for _, v := range vendorSpecificOf(entries) {
		if v.GetKind() == orphanToolResultKind {
			t.Errorf("%s: a tool_result landed as %q — its call was never joined, so that unit stays open in every reader downstream: %v",
				scenario, orphanToolResultKind, v.GetRaw().AsMap())
		}
	}
}

func vendorSpecificKindAllowed(kind string) bool {
	if allowedVendorSpecificKinds[kind] {
		return true
	}
	for _, prefix := range allowedVendorSpecificPrefixes {
		if strings.HasPrefix(kind, prefix) {
			return true
		}
	}
	return false
}

// requireNoUnparsedResidue: NOTHING the mocked vendor writes may fail to parse.
// `unparsed` is the reader's last resort for bytes that are not JSON at all, and
// the mock writes JSON lines exclusively.
func requireNoUnparsedResidue(t *testing.T, scenario string, entries []*storev1.StoreEntry) {
	t.Helper()
	for _, u := range unparsedOf(entries) {
		t.Errorf("%s: the sidecar could not PARSE a line the mocked vendor wrote: source=%q offset=%d error=%q",
			scenario, u.GetSource(), u.GetOffset(), u.GetParseError())
	}
}

// requireNoUnknownResidue: every discriminator the mock writes is one the
// converter models or deliberately withholds. An `unknown` is the converter
// saying it parsed a record and does not know what it is — for a scenario built
// from the corpus that is a producer defect by definition.
func requireNoUnknownResidue(t *testing.T, scenario string, entries []*storev1.StoreEntry) {
	t.Helper()
	for _, u := range unknownsOf(entries) {
		t.Errorf("%s: the sidecar parsed a record it does not model: field=%q discriminator=%q",
			scenario, u.GetDiscriminatorField(), u.GetDiscriminator())
	}
}

// requireDocumentedVendorSpecificKinds: withholding is deliberate and its
// classes are enumerated. A kind outside the documented set means the converter
// withheld something nobody decided to withhold.
func requireDocumentedVendorSpecificKinds(t *testing.T, scenario string, entries []*storev1.StoreEntry) {
	t.Helper()
	for _, kind := range vendorSpecificKinds(entries) {
		if !vendorSpecificKindAllowed(kind) {
			t.Errorf("%s: vendor_specific kind %q is outside the documented withholding classes", scenario, kind)
		}
	}
}

// requireBooksAreKnownAgents: every page line names a book that EXISTS as a
// file-plane identity — the transcript FILE's session uuid for a main agent
// (R9), the spawning call's tool_use_id from `agent-<id>.meta.json` for a
// subagent. A line in a book nobody can address is a line nobody can read.
func requireBooksAreKnownAgents(t *testing.T, scenario string, tree *mockTree, entries []*storev1.StoreEntry) {
	t.Helper()
	known := map[string]string{}
	for _, id := range tree.MainAgentIDs() {
		known[id] = "the transcript file's session uuid"
	}
	for _, id := range mockSubagentBookIDs(t, tree) {
		known[id] = "a subagent's meta.json toolUseId"
	}
	for _, line := range pageLinesOf(entries) {
		book := line.GetPageAgentId().GetValue()
		if _, ok := known[book]; !ok {
			t.Errorf("%s: a page line names the book %q, which is neither a transcript file's session uuid %v "+
				"nor a subagent's meta.json toolUseId %v", scenario, book, tree.MainAgentIDs(), mockSubagentBookIDs(t, tree))
		}
	}
}

// mockSubagentBookIDs reads each generated `agent-<id>.meta.json` and answers
// its `toolUseId` — the identity a subagent's own book is keyed by.
func mockSubagentBookIDs(t *testing.T, tree *mockTree) []string {
	t.Helper()
	var out []string
	for _, transcript := range tree.Subagents {
		meta := strings.TrimSuffix(transcript, ".jsonl") + ".meta.json"
		raw, err := os.ReadFile(meta)
		if err != nil {
			t.Fatalf("a subagent transcript has no metadata sidecar beside it (%s): %v", meta, err)
		}
		var fields struct {
			AgentType   string `json:"agentType"`
			Description string `json:"description"`
			ToolUseID   string `json:"toolUseId"`
			SpawnDepth  int    `json:"spawnDepth"`
		}
		if err := json.Unmarshal(raw, &fields); err != nil {
			t.Fatalf("decoding %s: %v", meta, err)
		}
		if fields.ToolUseID == "" {
			t.Fatalf("%s carries no toolUseId, which is the only key a subagent's book has", meta)
		}
		out = append(out, fields.ToolUseID)
	}
	sort.Strings(out)
	return out
}

// blockUnit is one text-or-thinking unit addressed as `<message.id>:<ordinal>`.
type blockUnit struct {
	messageID string
	ordinal   int
	hasUsage  bool
	// kind is the activity arm the unit carries, so two entries sharing an
	// identity can be told apart: the same arm twice is an UPSERT (the mock
	// duplicates a backgrounded agent's transcript into its spool, so the same
	// unit is legitimately written from two files), while two DIFFERENT arms
	// under one identity is a collision — one of them is unaddressable.
	kind string
	// activityID is the unit's own AgentActivityId, which must equal the key.
	activityID string
}

// mockBlockUnits reads every `activity:<message.id>:<ordinal>` unit off the wire.
// Tool-call units are addressed by their `tool_use_id` instead and are not here;
// they still CONSUME an ordinal, which is why the ordinals of the block units
// alone are asserted as a subset rather than as a dense run.
func mockBlockUnits(t *testing.T, entries []*storev1.StoreEntry) []blockUnit {
	t.Helper()
	var out []blockUnit
	for _, e := range entries {
		key := e.GetUpsertKey()
		if !strings.HasPrefix(key, "activity:") {
			continue
		}
		id := strings.TrimPrefix(key, "activity:")
		cut := strings.LastIndex(id, ":")
		if cut < 0 {
			continue // a tool call, addressed by its tool_use_id
		}
		ordinal, err := strconv.Atoi(id[cut+1:])
		if err != nil {
			continue // likewise: a tool_use_id that happens to contain a colon
		}
		activity := e.GetAgentUpdate().GetServeableFrame().GetAgentItem().GetAgentFrame().GetUpdate().GetActivity()
		out = append(out, blockUnit{
			messageID:  id[:cut],
			ordinal:    ordinal,
			hasUsage:   activity.GetUsage() != nil,
			kind:       fmt.Sprintf("%T", activity.GetItem()),
			activityID: activity.GetActivityId().GetValue(),
		})
	}
	return out
}

// requireBlockUnitsAreAddressedByBlock: an assistant message becomes SEVERAL
// units, one per content block, each addressed `<message.id>:<block ordinal>`
// with the ordinals running ACROSS the LINES that share the message id — the
// mock writes one line per block, so a converter that restarted the count per
// line would collide two units onto one identity.
//
// The ordinals are asserted DISTINCT rather than dense: a `tool_use` block is
// addressed by its own `tool_use_id` and an exempt block produces no unit at
// all, so a response legitimately yields a sparse set here. Distinctness is the
// property that matters — it is what makes the identity a per-block address.
func requireBlockUnitsAreAddressedByBlock(t *testing.T, scenario string, entries []*storev1.StoreEntry) {
	t.Helper()
	seen := map[string]blockUnit{}
	for _, unit := range mockBlockUnits(t, entries) {
		if unit.ordinal < 0 {
			t.Errorf("%s: block unit %s:%d has a negative ordinal", scenario, unit.messageID, unit.ordinal)
			continue
		}
		if unit.activityID != fmt.Sprintf("%s:%d", unit.messageID, unit.ordinal) {
			t.Errorf("%s: the unit keyed %s:%d carries the activity id %q, so its key and its identity disagree",
				scenario, unit.messageID, unit.ordinal, unit.activityID)
		}
		identity := fmt.Sprintf("%s:%d", unit.messageID, unit.ordinal)
		if prior, ok := seen[identity]; ok && prior.kind != unit.kind {
			t.Errorf("%s: the identity %s addresses two DIFFERENT units (%s and %s), so one of them is unaddressable",
				scenario, identity, prior.kind, unit.kind)
		}
		seen[identity] = unit
	}
}

// requireUsageOnTheFirstBlockOnly: EXACTLY ONE unit per API response carries
// `usage`, the unit for block 0. A consumer that sums units would otherwise
// over-count the bill by the number of blocks.
func requireUsageOnTheFirstBlockOnly(t *testing.T, scenario string, entries []*storev1.StoreEntry) {
	t.Helper()
	for _, unit := range mockBlockUnits(t, entries) {
		if unit.ordinal != 0 && unit.hasUsage {
			t.Errorf("%s: unit %s:%d carries usage, but only block 0 of a response may",
				scenario, unit.messageID, unit.ordinal)
		}
	}
}

// requireContextCutPageLine: the compaction and clear scenarios each land ONE
// context_cut page line of the main agent's book.
func requireContextCutPageLine(t *testing.T, scenario string, entries []*storev1.StoreEntry) {
	t.Helper()
	n := 0
	for _, line := range pageLinesOf(entries) {
		if contextCutOf(line) != nil {
			n++
		}
	}
	if n != 1 {
		t.Errorf("%s: expected exactly one AgentUpdate.context_cut page line, got %d", scenario, n)
	}
}

// requireAPIErrorPageLine: a `system/api_error` record is MID-TURN EVIDENCE and
// lands as its own page line, never as the turn's terminal.
func requireAPIErrorPageLine(t *testing.T, scenario string, entries []*storev1.StoreEntry) {
	t.Helper()
	for _, line := range pageLinesOf(entries) {
		if apiErrorOf(line) != nil {
			return
		}
	}
	t.Errorf("%s: no AgentUpdate.api_error page line was produced", scenario)
}

// requireContextBudgetWarning: the vendor's budget warning is a FILE-PLANE fact
// with no stream producer, so the sidecar is its only producer and it must
// arrive as a page line carrying the vendor's own sentence.
func requireContextBudgetWarning(t *testing.T, scenario string, entries []*storev1.StoreEntry) {
	t.Helper()
	for _, line := range pageLinesOf(entries) {
		warning := frameOf(line).GetUpdate().GetContextBudgetWarning()
		if warning == nil {
			continue
		}
		if warning.GetText() == "" {
			t.Errorf("%s: the context-budget warning landed with no text; the sentence IS the record", scenario)
		}
		return
	}
	t.Errorf("%s: no AgentUpdate.context_budget_warning page line was produced", scenario)
}

// requireKeepAliveStoresNothing: a keep-alive turn's records are read and
// converted, and not one of them becomes a page line. The keepalive arm is
// retired from the contract, so no entry can carry one.
func requireKeepAliveStoresNothing(t *testing.T, scenario string, entries []*storev1.StoreEntry) {
	t.Helper()
	for _, line := range pageLinesOf(entries) {
		t.Errorf("%s: a keep-alive turn produced a page line of book %q; a keep-alive stores nothing",
			scenario, line.GetPageAgentId().GetValue())
	}
}

// requireSubagentBook: a subagent's constituents form ITS OWN book, keyed by the
// spawning call's tool_use_id, and the spawn unit is a line in the PARENT's.
func requireSubagentBook(t *testing.T, scenario string, tree *mockTree, entries []*storev1.StoreEntry) {
	t.Helper()
	books := mockSubagentBookIDs(t, tree)
	if len(books) == 0 {
		t.Fatalf("%s: the scenario is declared to spawn a subagent, but the mock wrote no agent-<id>.meta.json", scenario)
	}
	for _, book := range books {
		if len(linesForBook(entries, book)) == 0 {
			t.Errorf("%s: the subagent book %q (its meta.json toolUseId) holds no page lines", scenario, book)
		}
	}
}

// requireBashRunReadableThroughTheStore: a detached shell's rows are read back
// through the REAL store's WatchBashRun — start, contiguous deltas, terminal —
// which is the only surface a consumer has for them.
func requireBashRunReadableThroughTheStore(t *testing.T, scenario string, in *mockIngest) {
	t.Helper()
	runs := mockDetachedRuns(in.Entries())
	if len(runs) == 0 {
		t.Fatalf("%s: the scenario is declared to launch a detached shell, but no bash rows were written", scenario)
	}
	ctx, cancel := testContext(t)
	defer cancel()
	for _, run := range runs {
		rows := awaitBashRunTerminal(ctx, t, in.Store.Client, run)
		requireBashReplayOrder(t, run, rows)
		requireLatestTail(t, run, rows)
	}
}

// mockDetachedRuns answers every detached run id the sidecar wrote bash rows for.
func mockDetachedRuns(entries []*storev1.StoreEntry) []string {
	seen := map[string]bool{}
	var out []string
	for _, b := range bashFramesOf(entries) {
		run := b.GetRun().GetValue()
		if run != "" && !seen[run] {
			seen[run] = true
			out = append(out, run)
		}
	}
	sort.Strings(out)
	return out
}

// requireExitCodeInTheTerminal: the spool's `EXIT=<code>` marker is the run's
// termination and rides the terminal row, never a delta.
func requireExitCodeInTheTerminal(t *testing.T, scenario string, in *mockIngest) {
	t.Helper()
	ctx, cancel := testContext(t)
	defer cancel()
	for _, run := range mockDetachedRuns(in.Entries()) {
		rows := awaitBashRunTerminal(ctx, t, in.Store.Client, run)
		terminal := rows[len(rows)-1]
		if terminal.GetSuccess().GetCompleted().GetTermination().GetExited() == nil {
			t.Errorf("%s: run %s terminated without an `exited` termination: %v",
				scenario, run, describeBashRows(rows[len(rows)-1:]))
		}
	}
}

// requireHeldTurnLandsWithoutAQuestion: a turn that is STOPPED rather than
// finished still had its content read off disk, and nothing on the way to the
// stop was a permission question.
//
// THE TERMINAL IS NOT ASSERTED HERE, deliberately. `AgentSuccess.interrupted`
// is a LIFECYCLE fact and the stream plane is its only producer — the sidecar's
// converters mint no AgentSuccess at all — so a file-plane subject demanding one
// would be asserting another system's duty against this one.
func requireHeldTurnLandsWithoutAQuestion(t *testing.T, scenario string, tree *mockTree, entries []*storev1.StoreEntry) {
	t.Helper()
	main := tree.LastMainAgentID()
	if len(linesForBook(entries, main)) == 0 {
		t.Errorf("%s: the held turn's records reached no page line of the main agent's book %q; a turn that is stopped is still read",
			scenario, main)
	}
	for _, line := range pageLinesOf(entries) {
		if q := frameOf(line).GetUpdate().GetQuestion(); q != nil {
			t.Errorf("%s: the held turn produced a question page line; this scenario reaches its stop with no permission question in the way: %v",
				scenario, q)
		}
	}
}

// requireBashPartialExtent: a settled shell whose output was TRUNCATED says so
// on this plane too.
//
// The stream plane and the file plane convert the same tool result into the same
// unit under one upsert key, so whichever row arrives last is what a reader
// sees. A file-plane row claiming the `whole` extent therefore ERASED the
// truncation summary the stream plane had already drawn, and `!bash-spill`
// reached the card as three lines of `y` with nothing saying the other 200 kB
// existed. This asserts the extent the sidecar states, not a merged view.
func requireBashPartialExtent(t *testing.T, scenario string, entries []*storev1.StoreEntry) {
	t.Helper()
	settled := 0
	for _, line := range pageLinesOf(entries) {
		bash := activityOf(line).GetBash().GetSuccess()
		if bash == nil {
			continue
		}
		settled++
		text := bash.GetCompleted().GetOutput().GetText()
		partial := text.GetPartial()
		if partial == nil {
			t.Errorf("%s: the settled shell's output extent = %T, want the partial arm carrying the omitted byte count",
				scenario, text.GetExtent())
			continue
		}
		if partial.GetBytesOmitted() == 0 {
			t.Errorf("%s: the settled shell's partial extent omits 0 bytes; the scenario declares a total far beyond what came back inline",
				scenario)
		}
		if partial.GetSpilled().GetPath() == "" {
			t.Errorf("%s: the settled shell's partial extent names no spill file, though the scenario's result declares `persistedOutputPath`",
				scenario)
		}
	}
	if settled == 0 {
		t.Errorf("%s: no settled shell reached a page line; there is nothing to state an extent about", scenario)
	}
}

// requireNoSettledShellForMovedWork: a command that MOVED to the background is
// not settled by this plane.
//
// The vendor returns the SAME receipt for a command that finished and one it
// launched -- empty output and a `backgroundTaskId` -- so a terminal built on it
// says the work concluded when it had not. Both planes write the unit under one
// upsert key, so a file-plane terminal arriving second REPLACED the stream
// plane's live card with a settled one carrying no output: a timed-out
// `sleep 600` drew as a command that ran and printed nothing while its own
// detached row ticked beside it. Found by the F42 playbook.
func requireNoSettledShellForMovedWork(t *testing.T, scenario string, entries []*storev1.StoreEntry) {
	t.Helper()
	started := 0
	for _, line := range pageLinesOf(entries) {
		bash := activityOf(line).GetBash()
		if bash == nil {
			continue
		}
		if bash.GetStart() != nil {
			started++
		}
		if bash.GetSuccess() != nil || bash.GetFailure() != nil {
			t.Errorf("%s: the file plane settled a shell whose work moved to the background: %v",
				scenario, bash.GetResult())
		}
	}
	if started == 0 {
		t.Errorf("%s: no shell START reached a page line, so the negative above asserts nothing", scenario)
	}
}
