package sessiondrv

import (
	"strings"

	datav1 "agentrepl/proto/agentshim/data/v1"
	frontendv1 "agentrepl/proto/agentshim/frontend/v1"
)

// slashCommandMachineryPrefixes are the envelope tags the Claude CLI opens its
// own slash-command bookkeeping records with.
//
// THE CLI BEHAVIOR THIS TRACKS. Running a slash command (/compact, /clear, any
// local command) makes the CLI append SYNTHETIC records to the transcript with
// `"type": "user"` and a content body that is not a prompt at all but markup
// describing the command it just ran, the caveat it wants the model to read, or
// the stdout the command produced. They are NOT flagged isMeta, so nothing in
// the envelope distinguishes them from something the user typed; the content
// head is the only signal the CLI leaves. Verified live forms:
//
//	<command-message>compact</command-message>\n<command-name>/compact</command-name>...
//	<local-command-caveat>Caveat: The messages below were generated by the user
//	  while running local commands. ...</local-command-caveat>
//	<local-command-stdout>...</local-command-stdout>
//
// A `<command-name>`-first record occurs too (the caveat wrapper is not always
// present and the block order varies), so each tag is matched on its own.
var slashCommandMachineryPrefixes = []string{
	"<command-message>",
	"<command-name>",
	"<local-command-caveat>",
	"<local-command-stdout>",
}

// isSlashCommandMachineryText reports whether one user-record body is the CLI's
// slash-command bookkeeping rather than a prompt.
//
// HEAD ONLY, after leading whitespace. A record the CLI synthesizes OPENS with
// its envelope tag; a human prompt that merely quotes or discusses one of these
// tags mid-sentence ("what does <command-name> mean?") is a real prompt and
// must reach the feed untouched. Matching anywhere in the body would swallow it.
func isSlashCommandMachineryText(content string) bool {
	head := strings.TrimLeft(content, " \t\r\n")
	for _, prefix := range slashCommandMachineryPrefixes {
		if strings.HasPrefix(head, prefix) {
			return true
		}
	}
	return false
}

// userRecordHead returns the leading text of a user record, or "" when the item
// is not a user record at all.
//
// Only the user_message arm is examined: the CLI writes its bookkeeping as a
// "user" record and nothing else in the conversation carries it. For a
// block-shaped body the FIRST text block is the head of the record — the later
// blocks of a caveat-wrapped record are more of the same bookkeeping, and a
// prompt whose first block is real text is a real prompt regardless of what
// follows.
func userRecordHead(it *frontendv1.ConversationItem) string {
	um := it.GetUserMessage()
	if um == nil {
		return ""
	}
	switch content := um.GetContent().(type) {
	case *datav1.ApiUserMessage_ContentString:
		return content.ContentString
	case *datav1.ApiUserMessage_ContentBlocks:
		for _, b := range content.ContentBlocks.GetBlocks() {
			if t := b.GetText(); t.GetText() != "" {
				return t.GetText()
			}
		}
	}
	return ""
}

// machineryEnvelope reports the envelope tag a conversation item is machinery
// under, or "" when the item is not a machinery user record.
func machineryEnvelope(it *frontendv1.ConversationItem) string {
	head := userRecordHead(it)
	if !isSlashCommandMachineryText(head) {
		return ""
	}
	trimmed := strings.TrimLeft(head, " \t\r\n")
	for _, prefix := range slashCommandMachineryPrefixes {
		if strings.HasPrefix(trimmed, prefix) {
			return prefix
		}
	}
	return ""
}

// withheldReason reports why a user record must not be RENDERED as a prompt
// bubble, or "" when it is a real prompt and belongs in the feed.
//
// TWO PRODUCERS OF NON-PROMPTS, one treatment. The CLI writes bookkeeping for
// its own slash commands; the daemon fires a read-directive of its own behind a
// `/clear` (promptdispatch.go). Neither is anything a human typed, both arrive
// as unflagged "user" transcript records, and both drew a purple bubble full of
// text the user never wrote.
func withheldReason(it *frontendv1.ConversationItem) string {
	if envelope := machineryEnvelope(it); envelope != "" {
		return "slash-command machinery " + envelope
	}
	if isMetapromptDirectiveText(userRecordHead(it)) {
		return "the daemon's own post-/clear metaprompt read-directive"
	}
	return ""
}

// withholdMachinery removes the CLI's slash-command bookkeeping records from a
// curated delta, loud-logging every one it takes out.
//
// WITHHELD, NOT DELETED. The store keeps the record — it is a faithful account
// of what the CLI wrote, and nothing here touches it. What is withheld is the
// RENDERED item: a purple prompt bubble full of `<command-message>` markup the
// user never typed, which is what both frontends drew before this existed.
//
// The delta itself is still pushed, empty items and all, so its through_seq
// still advances a frontend's cursor. The item is the only thing suppressed.
//
// Runs BEFORE attribution (promptecho.go): a machinery record must never claim
// an outstanding prompt receipt, which would retire the receipt for a real
// prompt and leave that prompt's own line unattributed behind it.
func (c *consumer) withholdMachinery(cd *frontendv1.ConversationDelta) {
	items := cd.GetItems()
	kept := items[:0]
	for _, it := range items {
		reason := withheldReason(it)
		if reason == "" {
			kept = append(kept, it)
			continue
		}
		c.logf("sessiondrv: user turn WITHHELD as %s ws=%q session=%s seq=%d uuid=%s — this is written as an unflagged \"user\" transcript record but is not a prompt; the store keeps it, the conversation feed does not",
			reason, c.workspace, c.sessionID, cd.GetThroughSeq(), it.GetUuid())
	}
	cd.Items = kept
}
