package main

// rotation_test.go — A ROTATED TRANSCRIPT IS NOT READ BEFORE ITS BOOK IS KNOWN.
//
// The forced interleaving these subjects pin is the one
// `TestSecondRotateUnderRotatedIdentity` lost at random under load: the vendor
// has written the rotated transcript (it opens with the `/clear` trio), and the
// reader sees it BEFORE the shim has written the link that names its book.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"agentrepl/shim-claude-sidecar/internal/discover"
)

const (
	// The rotated file's opening, in the shape the `identity-rotation-clear`
	// capture records: the caveat (isMeta), the expanded command envelope, and
	// the empty local-command stdout.
	caveatLine = `{"type":"user","isMeta":true,"message":{"role":"user","content":"<local-command-caveat>Caveat: generated by local commands.</local-command-caveat>"}}`
	clearLine  = `{"type":"user","message":{"role":"user","content":"<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>"}}`
	localLine  = `{"type":"system","subtype":"local_command","content":"","level":"info"}`
)

// recordedSibling arranges the conversation the shim ran in the project
// directory before it rotated: its first transcript, named by agent-id.json.
func recordedSibling(t *testing.T, h *harness) {
	t.Helper()
	h.mintIdentity(t, bookWorkspace, bookOriginal)
	h.transcript(t, bookOriginal, promptLine)
}

// writesUnderBook counts the batches that booked anything under book.
func writesUnderBook(store *fakeStore, book string) int {
	n := 0
	for _, batch := range store.writes {
		for _, entry := range batch.GetEntries() {
			if entry.GetAgentUpdate().GetTopLevel().GetValue() == book {
				n++
				break
			}
		}
	}
	return n
}

// TestARotatedTranscriptSeenBeforeItsLinkIsNotRead is the race itself, forced:
// nothing of the rotated file may reach the store under its own id. No record
// names the rotated id yet, so no active workspace owns it and it is not even
// admitted (active.go); the rotation hold below is the second guard.
func TestARotatedTranscriptSeenBeforeItsLinkIsNotRead(t *testing.T) {
	// Arrange.
	store := &fakeStore{}
	h := newHarness(t, store)
	recordedSibling(t, h)
	path := h.inactiveTranscript(t, bookRotated, caveatLine, clearLine, localLine)

	// Act.
	if err := h.sc.beginCycle(); err != nil {
		t.Fatalf("beginCycle: %v", err)
	}
	h.sc.discoverChanged()
	h.sc.pollAll()

	// Assert.
	if _, watched := h.sc.watchers[path]; watched {
		t.Error("the rotated transcript is watched before any record names its book")
	}
	if n := writesUnderBook(store, bookRotated); n != 0 {
		t.Errorf("%d batch(es) booked the rotated transcript under its own id %q; the conversation is split across two books", n, bookRotated)
	}
}

// heldRotation arranges the rotation hold's own subject: a rotated transcript
// beside a recorded sibling, offered to the hold directly. Admission would
// never offer it — no record names it yet — so the hold's verdicts are
// exercised on the target the scan produces.
func heldRotation(t *testing.T, h *harness, lines ...string) (string, discover.Target) {
	t.Helper()
	recordedSibling(t, h)
	path := h.inactiveTranscript(t, bookRotated, lines...)
	target := scannedTarget(t, h, path)
	if err := h.sc.beginCycle(); err != nil {
		t.Fatalf("beginCycle: %v", err)
	}
	return path, target
}

// TestTheRotationHoldIsStatedOnce: the hold begins at INFO, once, however many
// times it is re-examined.
func TestTheRotationHoldIsStatedOnce(t *testing.T) {
	// Arrange.
	h := newHarness(t, &fakeStore{})
	path, target := heldRotation(t, h, caveatLine, clearLine, localLine)

	// Act.
	h.sc.awaitsRotationLink(target)
	h.sc.awaitsRotationLink(target)

	// Assert.
	rec := h.requireOnce(t, "rotation-hold", "info")
	if got := ctxString(t, rec, "path"); got != path {
		t.Errorf("the hold names path %q, want %q", got, path)
	}
}

// TestTheLinkAdmitsTheRotationOnTheNextTick: once the shim names the book, the
// very next poll tick admits the file and reads it from its start, under the
// original's book. It is the rotation INTO an active workspace being followed.
func TestTheLinkAdmitsTheRotationOnTheNextTick(t *testing.T) {
	// Arrange.
	store := &fakeStore{}
	h := newHarness(t, store)
	recordedSibling(t, h)
	path := h.inactiveTranscript(t, bookRotated, caveatLine, clearLine, localLine)
	if err := h.sc.beginCycle(); err != nil {
		t.Fatalf("beginCycle: %v", err)
	}
	h.sc.discoverChanged()
	h.sc.pollAll()

	// Act: the shim writes its link, and no rescan runs before the next tick.
	h.linkVendorSession(t, bookWorkspace, bookRotated, bookOriginal)
	h.sc.discoverChanged()
	h.sc.pollAll()

	// Assert.
	w, watched := h.sc.watchers[path]
	if !watched {
		t.Fatal("the rotated transcript is still unwatched after its link landed")
	}
	if got := w.ctx.MainAgentID; got != bookOriginal {
		t.Errorf("the admitted transcript books to %q, want the original %q", got, bookOriginal)
	}
	if n := writesUnderBook(store, bookRotated); n != 0 {
		t.Errorf("%d batch(es) landed under the rotated id %q", n, bookRotated)
	}
	if n := writesUnderBook(store, bookOriginal); n == 0 {
		t.Error("nothing of the admitted transcript reached the original's book")
	}
}

// TestTheReleaseIsStated: the end of a hold is a lifecycle fact, stated at INFO.
func TestTheReleaseIsStated(t *testing.T) {
	// Arrange.
	h := newHarness(t, &fakeStore{})
	_, target := heldRotation(t, h, caveatLine, clearLine, localLine)
	h.sc.awaitsRotationLink(target)
	h.linkVendorSession(t, bookWorkspace, bookRotated, bookOriginal)
	h.sc.identity.Refresh()

	// Act.
	h.sc.awaitsRotationLink(target)

	// Assert.
	released := 0
	for _, rec := range h.opsAt(t, "rotation-hold", "info") {
		if strings.Contains(rec.Message, "released") {
			released++
		}
	}
	if released != 1 {
		t.Errorf("the release was stated %d time(s), want once", released)
	}
}

// TestAClearInADirectoryTheShimNeverRecordedIsNotHeld: the hold is only for a
// clear the shim will link; beside no shim conversation it holds nothing. (No
// active workspace owns such a file either, so it is never admitted.)
func TestAClearInADirectoryTheShimNeverRecordedIsNotHeld(t *testing.T) {
	// Arrange.
	h := newHarness(t, &fakeStore{})
	path := h.inactiveTranscript(t, bookRotated, caveatLine, clearLine, localLine)
	target := scannedTarget(t, h, path)
	if err := h.sc.beginCycle(); err != nil {
		t.Fatalf("beginCycle: %v", err)
	}

	// Act.
	held := h.sc.awaitsRotationLink(target)

	// Assert.
	if held {
		t.Error("a clear with no shim conversation beside it is held; nothing will ever link it")
	}
}

// TestATranscriptThatDoesNotOpenWithAClearIsNotHeld: an ordinary transcript
// beside a shim conversation is not held.
func TestATranscriptThatDoesNotOpenWithAClearIsNotHeld(t *testing.T) {
	// Arrange.
	h := newHarness(t, &fakeStore{})
	_, target := heldRotation(t, h, promptLine)

	// Act.
	held := h.sc.awaitsRotationLink(target)

	// Assert.
	if held {
		t.Error("a transcript that opens with an ordinary prompt was held")
	}
}

// TestATranscriptWithNoUserRecordYetIsHeld: the caveat alone cannot say whether
// the envelope follows, so the file waits for its next record.
func TestATranscriptWithNoUserRecordYetIsHeld(t *testing.T) {
	// Arrange.
	h := newHarness(t, &fakeStore{})
	_, target := heldRotation(t, h, caveatLine)

	// Act.
	held := h.sc.awaitsRotationLink(target)

	// Assert.
	if !held {
		t.Error("a transcript that has not yet said whether it opens with a clear was not held")
	}
}

// TestAnAlreadyLinkedRotationIsNotHeld: a link that landed first leaves nothing
// to wait for.
func TestAnAlreadyLinkedRotationIsNotHeld(t *testing.T) {
	// Arrange.
	h := newHarness(t, &fakeStore{})
	recordedSibling(t, h)
	h.linkVendorSession(t, bookWorkspace, bookRotated, bookOriginal)
	path := h.transcript(t, bookRotated, caveatLine, clearLine, localLine)

	// Act.
	if err := h.sc.beginCycle(); err != nil {
		t.Fatalf("beginCycle: %v", err)
	}

	// Assert.
	if _, watched := h.sc.watchers[path]; !watched {
		t.Error("a rotation whose link already exists was held")
	}
	h.requireNone(t, "rotation-hold", "info")
}

// TestAnUnreadableOpeningIsHeldAndWarned: the opening could not be examined, so
// whether the file continues a cleared conversation is unknown — it is held,
// and the failure is stated.
func TestAnUnreadableOpeningIsHeldAndWarned(t *testing.T) {
	// Arrange: a directory where the transcript should be makes the read fail
	// after the open succeeds.
	h := newHarness(t, &fakeStore{})
	recordedSibling(t, h)
	path := h.inactiveTranscript(t, bookRotated, clearLine)
	target := scannedTarget(t, h, path)
	if err := os.Remove(path); err != nil {
		t.Fatalf("removing %s: %v", path, err)
	}
	if err := os.Mkdir(path, 0o755); err != nil {
		t.Fatalf("creating %s: %v", path, err)
	}
	if err := h.sc.beginCycle(); err != nil {
		t.Fatalf("beginCycle: %v", err)
	}

	// Act.
	held := h.sc.awaitsRotationLink(target)

	// Assert.
	if !held {
		t.Error("a transcript whose opening could not be read was not held")
	}
	rec := h.requireOnce(t, "rotation-hold", "warn")
	if got := ctxString(t, rec, "path"); got != path {
		t.Errorf("the warning names path %q, want %q", got, path)
	}
}

// scannedTarget is the discovered target for a written transcript, as the scan
// produces it.
func scannedTarget(t *testing.T, h *harness, path string) discover.Target {
	t.Helper()
	for _, target := range h.sc.disc.Scan() {
		if target.Path == path {
			return target
		}
	}
	t.Fatalf("the scan did not discover %s", path)
	return discover.Target{}
}

// TestReadTranscriptOpening pins the opening read, one edge case per row.
func TestReadTranscriptOpening(t *testing.T) {
	many := make([]string, 0, openingRecordBudget+1)
	for range openingRecordBudget {
		many = append(many, localLine)
	}
	many = append(many, clearLine)
	cases := []struct {
		name    string
		content string
		want    transcriptOpening
	}{
		{"a clear after the caveat", caveatLine + "\n" + clearLine + "\n", openingClear},
		{"an ordinary prompt", promptLine + "\n", openingOther},
		{"only the meta caveat", caveatLine + "\n", openingUndetermined},
		{"an empty file", "", openingUndetermined},
		{"the envelope still being written", caveatLine + "\n" + clearLine, openingUndetermined},
		{"a malformed record before the clear", "{not json\n" + clearLine + "\n", openingClear},
		{"no user record within the budget", strings.Join(many, "\n") + "\n", openingOther},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			// Arrange.
			path := filepath.Join(t.TempDir(), "session.jsonl")
			if err := os.WriteFile(path, []byte(tc.content), 0o644); err != nil {
				t.Fatalf("writing %s: %v", path, err)
			}

			// Act.
			got, err := readTranscriptOpening(path)

			// Assert.
			if err != nil {
				t.Fatalf("readTranscriptOpening: %v", err)
			}
			if got != tc.want {
				t.Errorf("readTranscriptOpening = %s, want %s", got, tc.want)
			}
		})
	}
}

// TestReadTranscriptOpeningOfAMissingFileIsNotExist: the caller tells a vanished
// file from an unreadable one by this error.
func TestReadTranscriptOpeningOfAMissingFileIsNotExist(t *testing.T) {
	// Arrange.
	path := filepath.Join(t.TempDir(), "gone.jsonl")

	// Act.
	_, err := readTranscriptOpening(path)

	// Assert.
	if !os.IsNotExist(err) {
		t.Errorf("readTranscriptOpening of a missing file = %v, want a not-exist error", err)
	}
}
