package sessioncontroller

import (
	"testing"

	corev1 "agentrepl/proto/agentshim/core/v1"
	datav1 "agentrepl/proto/agentshim/data/v1"
	frontendv1 "agentrepl/proto/agentshim/frontend/v1"

	"google.golang.org/protobuf/types/known/anypb"
)

// --- the envelope predicate --------------------------------------------------

func TestIsSlashCommandMachineryText(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{
			name:    "command-message block (the /compact bookkeeping record)",
			content: "<command-message>compact</command-message>\n<command-name>/compact</command-name>\n<command-args></command-args>",
			want:    true,
		},
		{
			name:    "command-name first (the caveat wrapper is not always present)",
			content: "<command-name>/clear</command-name>\n<command-args></command-args>",
			want:    true,
		},
		{
			name:    "local-command-caveat wrapper",
			content: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>",
			want:    true,
		},
		{
			name:    "local-command-stdout record",
			content: "<local-command-stdout>total 8\ndrwxr-xr-x</local-command-stdout>",
			want:    true,
		},
		{
			name:    "leading newlines before the envelope",
			content: "\n\n<command-message>compact</command-message>",
			want:    true,
		},
		{
			name:    "leading spaces and tabs before the envelope",
			content: "  \t<local-command-stdout>ok</local-command-stdout>",
			want:    true,
		},
		{
			name:    "a real prompt that mentions the tag mid-text",
			content: "why does the transcript contain <command-name>/compact</command-name> records?",
			want:    false,
		},
		{
			name:    "a real prompt quoting the caveat mid-text",
			content: "The record began with <local-command-caveat> and I want it hidden.",
			want:    false,
		},
		{
			name:    "an ordinary prompt",
			content: "fix the feed pollution defect",
			want:    false,
		},
		{
			name:    "empty content",
			content: "",
			want:    false,
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Arrange / Act
			got := isSlashCommandMachineryText(tc.content)

			// Assert
			if got != tc.want {
				t.Errorf("isSlashCommandMachineryText(%q) = %v, want %v", tc.content, got, tc.want)
			}
		})
	}
}

// blockUserItem is a user item whose body arrives as content BLOCKS rather than
// a single string — the other shape the same record can take on the wire.
func blockUserItem(uuid string, texts ...string) *frontendv1.ConversationItem {
	blocks := make([]*datav1.ContentBlock, 0, len(texts))
	for _, txt := range texts {
		blocks = append(blocks, &datav1.ContentBlock{
			Block: &datav1.ContentBlock_Text{Text: &datav1.TextBlock{Text: txt}},
		})
	}
	return &frontendv1.ConversationItem{
		Uuid: uuid,
		Item: &frontendv1.ConversationItem_UserMessage{UserMessage: &datav1.ApiUserMessage{
			Content: &datav1.ApiUserMessage_ContentBlocks{
				ContentBlocks: &datav1.ApiContentBlocks{Blocks: blocks},
			},
		}},
	}
}

func TestMachineryEnvelopeReadsTheFirstTextBlock(t *testing.T) {
	// Arrange: a caveat-wrapped record whose bookkeeping continues in a second
	// block.
	item := blockUserItem("u1",
		"<local-command-caveat>Caveat: ...</local-command-caveat>",
		"<command-name>/compact</command-name>")

	// Act
	got := machineryEnvelope(item)

	// Assert
	if got != "<local-command-caveat>" {
		t.Errorf("machineryEnvelope = %q, want the first block's envelope", got)
	}
}

func TestABlockPromptWithRealFirstTextIsNotMachinery(t *testing.T) {
	// Arrange: a real prompt that happens to paste machinery markup below it.
	item := blockUserItem("u1",
		"here is what the CLI wrote:",
		"<command-message>compact</command-message>")

	// Act
	got := machineryEnvelope(item)

	// Assert
	if got != "" {
		t.Errorf("machineryEnvelope = %q, want a real prompt to be left alone", got)
	}
}

func TestAnAssistantItemIsNeverMachinery(t *testing.T) {
	// Arrange: only the user_message arm carries this markup.
	item := &frontendv1.ConversationItem{
		Uuid: "a1",
		Item: &frontendv1.ConversationItem_Agent{Agent: &frontendv1.AgentEmission{Emission: &frontendv1.AgentEmission_Response{Response: &frontendv1.AgentResponse{Body: &datav1.ApiAssistantMessage{Content: []*datav1.ContentBlock{
			{Block: &datav1.ContentBlock_Text{Text: &datav1.TextBlock{Text: "<command-name>/compact</command-name>"}}},
		}},
		}}}},
	}

	// Act
	got := machineryEnvelope(item)

	// Assert
	if got != "" {
		t.Errorf("machineryEnvelope = %q, want assistant content left alone", got)
	}
}

// --- the curator --------------------------------------------------------------

const compactMachinery = "<command-message>compact</command-message>\n<command-name>/compact</command-name>\n<command-args></command-args>"

func TestAMachineryUserLineIsWithheldFromTheFeed(t *testing.T) {
	// Arrange
	h := newQueueHarness(t, nil)

	// Act: the CLI's own /compact bookkeeping arrives as a "user" record.
	h.controller().consumer.Consume(transcriptUserEvent(t, 12, "u-machinery", compactMachinery))

	// Assert: the user never typed it, so no bubble is drawn for it.
	if turns := h.userTurns(); len(turns) != 0 {
		t.Fatalf("pushed %d user turn(s) for a machinery record, want none", len(turns))
	}
}

func TestARealPromptBesideMachineryStillReachesTheFeed(t *testing.T) {
	// Arrange
	h := newQueueHarness(t, nil)

	// Act
	h.controller().consumer.Consume(transcriptUserEvent(t, 12, "u-machinery", compactMachinery))
	h.controller().consumer.Consume(transcriptUserEvent(t, 13, "u-real", "carry on"))

	// Assert
	turns := h.userTurns()
	if len(turns) != 1 {
		t.Fatalf("pushed %d user turn(s), want the real prompt alone", len(turns))
	}
	if got := turns[0].item.GetUuid(); got != "u-real" {
		t.Errorf("pushed user turn uuid = %q, want the real prompt u-real", got)
	}
}

func TestWithholdingAMachineryLineIsLoud(t *testing.T) {
	// Arrange: a silent drop is indistinguishable from a lost record.
	cl := &logCapture{}
	h := newQueueHarnessWithPusher(t, nil, nil, cl.logf)

	// Act
	h.controller().consumer.Consume(transcriptUserEvent(t, 12, "u-machinery", compactMachinery))

	// Assert
	if !cl.contains("user turn WITHHELD as slash-command machinery") {
		t.Error("no loud line accounts for the withheld machinery record")
	}
	if !cl.contains("uuid=u-machinery") {
		t.Error("the loud line does not name the record it withheld")
	}
}

func TestAWithheldMachineryLineStillAdvancesTheSeq(t *testing.T) {
	// Arrange
	h := newQueueHarness(t, nil)

	// Act
	h.controller().consumer.Consume(transcriptUserEvent(t, 12, "u-machinery", compactMachinery))

	// Assert: the record is retained and seq-accounted exactly as any other —
	// only the rendered item is withheld.
	if got := h.controller().consumer.newestRetainedSeq(); got != 12 {
		t.Errorf("newest retained seq = %d, want the machinery record's own 12", got)
	}
	var delta *frontendv1.ConversationDelta
	h.push.mu.Lock()
	for _, cd := range h.push.convo {
		if cd.GetThroughSeq() == 12 {
			delta = cd
		}
	}
	h.push.mu.Unlock()
	if delta == nil {
		t.Fatal("no delta carried through_seq 12, so no frontend cursor advanced past the machinery record")
	}
	if got := len(delta.GetItems()); got != 0 {
		t.Errorf("the through_seq-12 delta carried %d item(s), want none", got)
	}
}

func TestAMachineryLineDoesNotRaiseTheReplayFloor(t *testing.T) {
	// Arrange: the bookkeeping for /compact is NOT the compaction itself — only
	// the sidecar's first-class ContextCompacted floors the conversation.
	h := newQueueHarness(t, nil)

	// Act
	h.controller().consumer.Consume(transcriptUserEvent(t, 12, "u-machinery", compactMachinery))

	// Assert
	if seq := h.controller().consumer.floors.NewestClearOrCompactSeq("s1"); seq != 0 {
		t.Errorf("replay floor = %d after a machinery record, want none", seq)
	}
}

func TestAMachineryLineClaimsNoPromptReceipt(t *testing.T) {
	// Arrange: a real submit is outstanding when the CLI writes its bookkeeping.
	h := newQueueHarness(t, nil)
	if err := h.submitAs("r1", "hello there"); err != nil {
		t.Fatalf("submit: %v", err)
	}

	// Act: the machinery record arrives BEFORE the real prompt's durable line.
	h.controller().consumer.Consume(transcriptUserEvent(t, 12, "u-machinery", compactMachinery))

	// Assert: the receipt is still outstanding for the line that really answers
	// it — a machinery record retiring it would leave the real prompt's own line
	// unattributed and the bubble duplicated.
	if got := len(h.controller().consumer.snapshotEchoes()); got != 1 {
		t.Fatalf("outstanding receipts = %d, want the real submit's still held", got)
	}
}

func TestTheRealLineIsStillAttributedAfterAMachineryLine(t *testing.T) {
	// Arrange
	h := newQueueHarness(t, nil)
	if err := h.submitAs("r1", "hello there"); err != nil {
		t.Fatalf("submit: %v", err)
	}

	// Act
	h.controller().consumer.Consume(transcriptUserEvent(t, 12, "u-machinery", compactMachinery))
	h.controller().consumer.Consume(transcriptUserEvent(t, 13, "u-real", "hello there"))

	// Assert
	turns := h.userTurns()
	if len(turns) != 2 {
		t.Fatalf("pushed %d user turn(s), want the receipt and the real durable line", len(turns))
	}
	if got := turns[1].item.GetRequestId(); got != "r1" {
		t.Errorf("durable line request_id = %q, want the submit's id r1", got)
	}
}

func TestAReplayedMachineryLineIsWithheldToo(t *testing.T) {
	// Arrange: a resync must not re-pollute a feed the live path kept clean.
	h := newQueueHarness(t, nil)

	// Act
	h.controller().consumer.pushConversation(transcriptUserEvent(t, 12, "u-machinery", compactMachinery), false)

	// Assert
	if turns := h.userTurns(); len(turns) != 0 {
		t.Fatalf("replayed %d user turn(s) for a machinery record, want none", len(turns))
	}
}

// machineryStreamEvent is the same bookkeeping arriving on the STREAM plane
// (a bare UserMessage rather than a transcript line).
func machineryStreamEvent(t *testing.T, seq uint64, text string) *corev1.Event {
	t.Helper()
	a, err := anypb.New(&datav1.UserMessage{
		Message: &datav1.ApiUserMessage{
			Content: &datav1.ApiUserMessage_ContentString{ContentString: text},
		},
	})
	if err != nil {
		t.Fatalf("anypb.New: %v", err)
	}
	return &corev1.Event{SessionId: "vendor-uuid", Seq: seq, Payload: &corev1.Event_Vendor{Vendor: a}}
}

func TestMachineryOnTheStreamPlaneIsWithheldToo(t *testing.T) {
	// Arrange
	h := newQueueHarness(t, nil)

	// Act
	h.controller().consumer.Consume(machineryStreamEvent(t, 12, compactMachinery))

	// Assert
	if turns := h.userTurns(); len(turns) != 0 {
		t.Fatalf("pushed %d user turn(s) for a stream-plane machinery record, want none", len(turns))
	}
}
