package sessioncontroller

import (
	"fmt"
	"strings"

	datav1 "agentrepl/proto/agentshim/data/v1"
	frontendv1 "agentrepl/proto/agentshim/frontend/v1"

	"claude-repld/internal/frontend"
)

// machinery.go — CLASSIFYING THE CLI'S OWN SLASH-COMMAND RECORDS.
//
// WHAT CHANGED, AND WHY. This file used to RECOGNIZE these records and throw
// them away: the only thing wrong with them was that they rendered as a purple
// prompt bubble full of markup nobody typed, so suppressing the bubble looked
// like the whole fix. It was not. A slash command the CLI really ran is a fact
// about the conversation — the user did something to the session, and the
// transcript has a durable record of it — and discarding the record left the
// feed with no account of it at all, which a reload could not repair because
// there was nothing to reload. The record is now CLASSIFIED instead: its
// payload becomes a DaemonInterceptedCommandItem naming the command, on the
// same message identity the CLI wrote, so it reloads as itself.

// slashCommandMachineryPrefixes are the envelope tags the Claude CLI opens its
// own slash-command bookkeeping records with.
//
// THE CLI BEHAVIOR THIS TRACKS. Running a slash command makes the CLI append
// SYNTHETIC records to the transcript whose body is not a prompt at all but
// markup describing the command it just ran, the caveat it wants the model to
// read, or the stdout the command produced. There are TWO SHAPES, and only one
// of them is matched by the tags below:
//
// SHAPE A — a `"type": "user"` record, NOT flagged isMeta, carrying a
// `promptId`. Nothing in its envelope distinguishes it from something the user
// typed, so for this shape the content head is the only signal the CLI leaves.
// Verified live forms:
//
//	<command-message>compact</command-message>\n<command-name>/compact</command-name>...
//	<local-command-caveat>Caveat: The messages below were generated by the user
//	  while running local commands. ...</local-command-caveat>
//	<local-command-stdout>...</local-command-stdout>
//
// SHAPE B — a `"type": "system"` record with `"subtype": "local_command"`,
// which IS flagged isMeta and carries NO promptId. Its ENVELOPE is structured
// evidence, so this shape is identified by the envelope and never by its text
// (see machineryShapeOf). The blanket claim that these records carry nothing in
// the envelope was true of shape A only, and stating it of both is what kept
// shape B being read through its prose.
//
// A `<command-name>`-first record occurs too (the caveat wrapper is not always
// present and the block order varies), so each tag is matched on its own.
var slashCommandMachineryPrefixes = []string{
	"<command-message>",
	"<command-name>",
	"<local-command-caveat>",
	"<local-command-stdout>",
}

// isSlashCommandMachineryText reports whether one user-record body is the CLI's
// slash-command bookkeeping rather than a prompt.
//
// HEAD ONLY, after leading whitespace. A record the CLI synthesizes OPENS with
// its envelope tag; a human prompt that merely quotes or discusses one of these
// tags mid-sentence ("what does <command-name> mean?") is a real prompt and
// must reach the feed untouched. Matching anywhere in the body would swallow it.
func isSlashCommandMachineryText(content string) bool {
	head := strings.TrimLeft(content, " \t\r\n")
	for _, prefix := range slashCommandMachineryPrefixes {
		if strings.HasPrefix(head, prefix) {
			return true
		}
	}
	return false
}

// userRecordHead returns the leading text of a user record, or "" when the item
// is not a user record at all.
//
// Only the user_message arm is examined: the CLI writes its bookkeeping as a
// "user" record and nothing else in the conversation carries it. For a
// block-shaped body the FIRST text block is the head of the record — the later
// blocks of a caveat-wrapped record are more of the same bookkeeping, and a
// prompt whose first block is real text is a real prompt regardless of what
// follows.
func userRecordHead(it *frontendv1.Message) string {
	um := it.GetUserMessage()
	if um == nil {
		return ""
	}
	switch content := um.GetContent().(type) {
	case *datav1.ApiUserMessage_ContentString:
		return content.ContentString
	case *datav1.ApiUserMessage_ContentBlocks:
		for _, b := range content.ContentBlocks.GetBlocks() {
			if t := b.GetText(); t.GetText() != "" {
				return t.GetText()
			}
		}
	}
	return ""
}

// userRecordBody returns EVERY text block of a user record joined in order.
//
// The HEAD decides whether a record is machinery at all; the BODY is where the
// command's name is looked for once that verdict is in. They are separate reads
// on purpose: a caveat-wrapped record opens with the caveat and names the
// command in a later block, so reading the name from the head alone would leave
// exactly the records that need classifying unnamed. Widening the head read to
// the whole body instead would re-open the swallowing this file exists to
// prevent, because a human prompt could then be machinery by its third
// paragraph.
func userRecordBody(it *frontendv1.Message) string {
	um := it.GetUserMessage()
	if um == nil {
		return ""
	}
	switch content := um.GetContent().(type) {
	case *datav1.ApiUserMessage_ContentString:
		return content.ContentString
	case *datav1.ApiUserMessage_ContentBlocks:
		var sb strings.Builder
		for _, b := range content.ContentBlocks.GetBlocks() {
			if t := b.GetText(); t.GetText() != "" {
				sb.WriteString(t.GetText())
				sb.WriteString("\n")
			}
		}
		return sb.String()
	}
	return ""
}

// machineryEnvelope reports the envelope tag a conversation item is machinery
// under, or "" when the item is not a machinery user record.
//
// SHAPE A ONLY. This is the content-head test, which is all shape A leaves
// behind; shape B is decided by machineryShapeOf before this is ever consulted.
func machineryEnvelope(it *frontendv1.Message) string {
	head := userRecordHead(it)
	if !isSlashCommandMachineryText(head) {
		return ""
	}
	trimmed := strings.TrimLeft(head, " \t\r\n")
	for _, prefix := range slashCommandMachineryPrefixes {
		if strings.HasPrefix(trimmed, prefix) {
			return prefix
		}
	}
	return ""
}

// machineryShape names WHICH of the CLI's two synthetic record shapes an item
// is, or that it is neither.
type machineryShape int

const (
	// notMachinery is a record the CLI did not synthesize — an ordinary prompt.
	notMachinery machineryShape = iota
	// shapeAUserRecord is the `"type": "user"` shape, recognized by its content
	// head because its envelope says nothing.
	shapeAUserRecord
	// shapeBLocalCommand is the `"type": "system"` / `"subtype":
	// "local_command"` shape, recognized by its envelope.
	shapeBLocalCommand
)

// machineryShapeOf classifies one curated item against the two shapes.
//
// THE ENVELOPE TEST RUNS FIRST, AND IT WINS. Shape B's `local_command` subtype
// and isMeta flag are the harness's own structured statement about the record,
// which cannot be spoofed by what the record happens to SAY; the content head
// is prose, and prose is what a `/context` dump full of arbitrary stdout is
// made of. Consulting the head first would leave a shape B record whose stdout
// opens with anything other than the four tags above classified as a prompt —
// the exact defect the ordering here removes.
//
// An item with no envelope in this delta falls through to the head test rather
// than being treated as shape B: an absent envelope is an absent claim, and the
// records that reach here without one are the ordinary conversation's.
func machineryShapeOf(it *frontendv1.Message, env frontend.RecordEnvelope, haveEnv bool) machineryShape {
	if haveEnv && env.LocalCommandSubtype && env.IsMeta {
		return shapeBLocalCommand
	}
	if machineryEnvelope(it) != "" {
		return shapeAUserRecord
	}
	return notMachinery
}

// machineryCommandName extracts the `/name` from a `<command-name>` tag
// anywhere in a machinery record's body, or "" when the record names none.
//
// Read from the tag rather than guessed from the surrounding prose: the tag is
// the CLI's own statement of which command it ran, and it is the only part of
// these records that is structured at all.
func machineryCommandName(body string) string {
	const open, close = "<command-name>", "</command-name>"
	start := strings.Index(body, open)
	if start < 0 {
		return ""
	}
	rest := body[start+len(open):]
	end := strings.Index(rest, close)
	if end < 0 {
		return ""
	}
	return strings.TrimSpace(rest[:end])
}

// machineryCommand resolves a machinery record's body to the session command it
// records, or UNSPECIFIED when it names none the schema knows.
//
// The resolution goes through lookupSessionCommand — the SAME closed table the
// daemon recognizes an INBOUND submit with, read off the SessionCommand enum's
// own options — so a command cannot be spelled one way on the way in and
// another way on the way out.
func machineryCommand(body string) frontendv1.SessionCommand {
	name := machineryCommandName(body)
	if name == "" {
		return frontendv1.SessionCommand_SESSION_COMMAND_UNSPECIFIED
	}
	command, _ := lookupSessionCommand(name)
	return command
}

// withheldReason reports why a user record must not be RENDERED as a prompt,
// or "" when it is a real prompt and belongs in the feed.
//
// It now covers only the daemon's OWN read-directive: the CLI's machinery is
// classified rather than withheld (classifyMachinery), so the two no longer
// share a treatment even though they still share a producer problem — neither
// is anything a human typed, and both arrive as unflagged "user" transcript
// records.
func withheldReason(it *frontendv1.Message) string {
	if isMetapromptDirectiveText(userRecordHead(it)) {
		return "a standalone metaprompt read-directive"
	}
	return ""
}

// asInterceptedCommand REWRITES one curated item in place into the feed's
// record that the command was invoked.
//
// THE IDENTITY IS THE RECORD'S OWN, deliberately. The item keeps the uuid the
// CLI wrote, its timestamp and its lineage, and only the PAYLOAD changes. That
// is what makes two slash commands issued moments apart impossible to confuse:
// each is the message the transcript already distinguishes, so nothing here
// depends on their order of arrival, and a replay re-derives the same answer
// for the same record rather than a different one for a different position.
func asInterceptedCommand(it *frontendv1.Message, command frontendv1.SessionCommand) {
	it.Payload = &frontendv1.Message_DaemonInterceptedCommand{
		DaemonInterceptedCommand: &frontendv1.DaemonInterceptedCommandItem{Command: command},
	}
	// TODO(slash-ephemeral-constructor): set the message's `durability` arm here
	// — DURABLE for shape A, which has a transcript record behind it, EPHEMERAL
	// for shape B, which the contract rules out of the durable set. Neither arm
	// is set from this file on purpose: the ephemeral side must go through the
	// REFUSING ephemeral constructor that enforces the lineage rules (an
	// ephemeral message is always a feed row, is never a parent, and never names
	// a durable parent), and that constructor is owned by the sibling scope that
	// introduces it. Constructing either arm by hand here would be the second
	// construction path those rules exist to prevent.
}

// classifyMachinery turns the CLI's slash-command bookkeeping records into the
// feed's record of the commands they report, loud-logging every one it rewrites
// and every one it cannot name.
//
// CLASSIFIED, NOT WITHHELD. What used to be suppressed here was the RENDERING —
// a purple prompt bubble full of `<command-message>` markup the user never
// typed — and suppressing the whole record to be rid of the bubble threw away
// the fact along with it. The record is now delivered as what it actually is:
// a DaemonInterceptedCommandItem carrying the command's identity and no text,
// so there is no field for the markup to come back through.
//
// A RECORD THAT NAMES NO COMMAND IS STILL WITHHELD, and still loudly. Some
// machinery records are pure `<local-command-stdout>` with no `<command-name>`
// anywhere in them, and a DaemonInterceptedCommandItem whose command is
// UNSPECIFIED is a malformed frame a receiver must reject. Withholding is the
// honest answer for those, and it is the behaviour this file already had.
//
// Runs BEFORE attribution (promptecho.go): a machinery record must never claim
// an outstanding prompt receipt, which would retire the receipt for a real
// prompt and leave that prompt's own line unattributed behind it. Classifying
// it strengthens that, because a classified record no longer carries a
// user_message arm for the attribution to look at.
func (c *consumer) classifyMachinery(cd *frontendv1.ConversationDelta, envs map[string]frontend.RecordEnvelope) {
	c.withholdItems(cd, func(it *frontendv1.Message) withholdVerdict {
		env, haveEnv := envs[it.GetUuid()]
		switch shape := machineryShapeOf(it, env, haveEnv); shape {
		case notMachinery:
			if reason := withheldReason(it); reason != "" {
				return withholdItem(fmt.Sprintf("session-controller: user turn WITHHELD as %s ws=%q session=%s seq=%d uuid=%s — this is written as an unflagged \"user\" transcript record but is not a prompt; the store keeps it, the conversation feed does not",
					reason, c.workspace, c.sessionID, cd.GetThroughSeq(), it.GetUuid()))
			}
			return keepItem
		default:
			command := machineryCommand(userRecordBody(it))
			if command == frontendv1.SessionCommand_SESSION_COMMAND_UNSPECIFIED {
				return withholdItem(fmt.Sprintf("session-controller: slash-command machinery WITHHELD UNNAMED ws=%q session=%s seq=%d uuid=%s shape=%s prompt_id=%q — the record is the CLI's own slash-command bookkeeping but carries no <command-name> tag, so there is no command identity to classify it as; an UNSPECIFIED command is a malformed frame, so the item is withheld rather than pushed half-stated",
					c.workspace, c.sessionID, cd.GetThroughSeq(), it.GetUuid(), shape, env.PromptID))
			}
			asInterceptedCommand(it, command)
			c.logf("session-controller: slash-command machinery CLASSIFIED ws=%q session=%s seq=%d uuid=%s shape=%s command=%s prompt_id=%q — the CLI's own record of a command it ran, delivered as a DaemonInterceptedCommandItem on the record's own identity rather than as a prompt bubble full of markup nobody typed",
				c.workspace, c.sessionID, cd.GetThroughSeq(), it.GetUuid(), shape, command.String(), env.PromptID)
			return keepItem
		}
	})
}

// String names a shape for the log, so an operator reading a classification
// line can tell WHICH evidence decided it.
func (s machineryShape) String() string {
	switch s {
	case shapeAUserRecord:
		return "A/user-record-content-head"
	case shapeBLocalCommand:
		return "B/system-local_command-envelope"
	default:
		return "none"
	}
}
