package sessioncontroller

import (
	"testing"

	corev1 "agentrepl/proto/agentshim/core/v1"
	datav1 "agentrepl/proto/agentshim/data/v1"
	frontendv1 "agentrepl/proto/frontend/v1"

	"google.golang.org/protobuf/types/known/anypb"
)

// --- the envelope predicate --------------------------------------------------

func TestIsSlashCommandMachineryText(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{
			name:    "command-message block (the /compact bookkeeping record)",
			content: "<command-message>compact</command-message>\n<command-name>/compact</command-name>\n<command-args></command-args>",
			want:    true,
		},
		{
			name:    "command-name first (the caveat wrapper is not always present)",
			content: "<command-name>/clear</command-name>\n<command-args></command-args>",
			want:    true,
		},
		{
			name:    "local-command-caveat wrapper",
			content: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>",
			want:    true,
		},
		{
			name:    "local-command-stdout record",
			content: "<local-command-stdout>total 8\ndrwxr-xr-x</local-command-stdout>",
			want:    true,
		},
		{
			name:    "leading newlines before the envelope",
			content: "\n\n<command-message>compact</command-message>",
			want:    true,
		},
		{
			name:    "leading spaces and tabs before the envelope",
			content: "  \t<local-command-stdout>ok</local-command-stdout>",
			want:    true,
		},
		{
			name:    "a real prompt that mentions the tag mid-text",
			content: "why does the transcript contain <command-name>/compact</command-name> records?",
			want:    false,
		},
		{
			name:    "a real prompt quoting the caveat mid-text",
			content: "The record began with <local-command-caveat> and I want it hidden.",
			want:    false,
		},
		{
			name:    "an ordinary prompt",
			content: "fix the feed pollution defect",
			want:    false,
		},
		{
			name:    "empty content",
			content: "",
			want:    false,
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			// Arrange / Act
			got := isSlashCommandMachineryText(tc.content)

			// Assert
			if got != tc.want {
				t.Errorf("isSlashCommandMachineryText(%q) = %v, want %v", tc.content, got, tc.want)
			}
		})
	}
}

// blockUserItem is a user item whose body arrives as content BLOCKS rather than
// a single string — the other shape the same record can take on the wire.
func blockUserItem(uuid string, texts ...string) *frontendv1.Message {
	blocks := make([]*datav1.ContentBlock, 0, len(texts))
	for _, txt := range texts {
		blocks = append(blocks, &datav1.ContentBlock{
			Block: &datav1.ContentBlock_Text{Text: &datav1.TextBlock{Text: txt}},
		})
	}
	return &frontendv1.Message{
		Uuid: uuid,
		Payload: &frontendv1.Message_UserMessage{UserMessage: &datav1.ApiUserMessage{
			Content: &datav1.ApiUserMessage_ContentBlocks{
				ContentBlocks: &datav1.ApiContentBlocks{Blocks: blocks},
			},
		}},
	}
}

func TestMachineryEnvelopeReadsTheFirstTextBlock(t *testing.T) {
	// Arrange: a caveat-wrapped record whose bookkeeping continues in a second
	// block.
	item := blockUserItem("u1",
		"<local-command-caveat>Caveat: ...</local-command-caveat>",
		"<command-name>/compact</command-name>")

	// Act
	got := machineryEnvelope(item)

	// Assert
	if got != "<local-command-caveat>" {
		t.Errorf("machineryEnvelope = %q, want the first block's envelope", got)
	}
}

func TestABlockPromptWithRealFirstTextIsNotMachinery(t *testing.T) {
	// Arrange: a real prompt that happens to paste machinery markup below it.
	item := blockUserItem("u1",
		"here is what the CLI wrote:",
		"<command-message>compact</command-message>")

	// Act
	got := machineryEnvelope(item)

	// Assert
	if got != "" {
		t.Errorf("machineryEnvelope = %q, want a real prompt to be left alone", got)
	}
}

func TestAnAssistantItemIsNeverMachinery(t *testing.T) {
	// Arrange: only the user_message arm carries this markup.
	item := &frontendv1.Message{
		Uuid: "a1",
		Payload: &frontendv1.Message_Agent{Agent: &frontendv1.AgentEmission{Emission: &frontendv1.AgentEmission_Response{Response: &frontendv1.AgentResponse{Body: &datav1.ApiAssistantMessage{Content: []*datav1.ContentBlock{
			{Block: &datav1.ContentBlock_Text{Text: &datav1.TextBlock{Text: "<command-name>/compact</command-name>"}}},
		}},
		}}}},
	}

	// Act
	got := machineryEnvelope(item)

	// Assert
	if got != "" {
		t.Errorf("machineryEnvelope = %q, want assistant content left alone", got)
	}
}

// --- the curator --------------------------------------------------------------

const compactMachinery = "<command-message>compact</command-message>\n<command-name>/compact</command-name>\n<command-args></command-args>"

func TestAMachineryUserLineIsNeverDrawnAsAPrompt(t *testing.T) {
	// Arrange
	h := newQueueHarness(t, nil)

	// Act: the CLI's own /compact bookkeeping arrives as a "user" record.
	h.controller().consumer.Consume(transcriptUserEvent(t, 12, "u-machinery", compactMachinery))

	// Assert: the user never typed it, so no work is drawn for it.
	if turns := h.userTurns(); len(turns) != 0 {
		t.Fatalf("pushed %d user turn(s) for a machinery record, want none", len(turns))
	}
}

func TestARealPromptBesideMachineryStillReachesTheFeed(t *testing.T) {
	// Arrange
	h := newQueueHarness(t, nil)

	// Act
	h.controller().consumer.Consume(transcriptUserEvent(t, 12, "u-machinery", compactMachinery))
	h.controller().consumer.Consume(transcriptUserEvent(t, 13, "u-real", "carry on"))

	// Assert
	turns := h.userTurns()
	if len(turns) != 1 {
		t.Fatalf("pushed %d user turn(s), want the real prompt alone", len(turns))
	}
	if got := turns[0].item.GetUuid(); got != "u-real" {
		t.Errorf("pushed user turn uuid = %q, want the real prompt u-real", got)
	}
}

func TestClassifyingAMachineryLineIsLoud(t *testing.T) {
	// Arrange: a silent rewrite is indistinguishable from a lost record.
	cl := &logCapture{}
	h := newQueueHarnessWithPusher(t, nil, nil, cl.logf)

	// Act
	h.controller().consumer.Consume(transcriptUserEvent(t, 12, "u-machinery", compactMachinery))

	// Assert
	if !cl.contains("slash-command machinery CLASSIFIED") {
		t.Error("no loud line accounts for the classified machinery record")
	}
	if !cl.contains("uuid=u-machinery") {
		t.Error("the loud line does not name the record it classified")
	}
}

func TestAnUnnamedMachineryLineIsStillWithheldLoudly(t *testing.T) {
	// Arrange: a stdout-only record names no command, and an UNSPECIFIED
	// command is a malformed frame rather than a half-stated item.
	cl := &logCapture{}
	h := newQueueHarnessWithPusher(t, nil, nil, cl.logf)

	// Act
	h.controller().consumer.Consume(transcriptUserEvent(t, 12, "u-stdout", "<local-command-stdout>total 8</local-command-stdout>"))

	// Assert
	if !cl.contains("slash-command machinery WITHHELD UNNAMED") {
		t.Error("no loud line accounts for the machinery record that named no command")
	}
}

func TestAClassifiedMachineryLineStillAdvancesTheSeq(t *testing.T) {
	// Arrange
	h := newQueueHarness(t, nil)

	// Act
	h.controller().consumer.Consume(transcriptUserEvent(t, 12, "u-machinery", compactMachinery))

	// Assert: the record is retained and seq-accounted exactly as any other.
	if got := h.controller().consumer.newestRetainedSeq(); got != 12 {
		t.Errorf("newest retained seq = %d, want the machinery record's own 12", got)
	}
	var delta *frontendv1.ConversationDelta
	h.push.mu.Lock()
	for _, cd := range h.push.convo {
		if cd.GetThroughSeq() == 12 {
			delta = cd
		}
	}
	h.push.mu.Unlock()
	if delta == nil {
		t.Fatal("no delta carried through_seq 12, so no frontend cursor advanced past the machinery record")
	}
	if got := len(delta.GetMessages()); got != 1 {
		t.Errorf("the through_seq-12 delta carried %d item(s), want the classified command", got)
	}
}

func TestAMachineryLineDoesNotRaiseTheReplayFloor(t *testing.T) {
	// Arrange: the bookkeeping for /compact is NOT the compaction itself — only
	// the sidecar's first-class ContextCompacted floors the conversation.
	h := newQueueHarness(t, nil)

	// Act
	h.controller().consumer.Consume(transcriptUserEvent(t, 12, "u-machinery", compactMachinery))

	// Assert
	if seq := h.controller().consumer.floors.NewestClearOrCompactSeq("s1"); seq != 0 {
		t.Errorf("replay floor = %d after a machinery record, want none", seq)
	}
}

func TestAMachineryLineIsNotDrawnAsTheOutstandingPrompt(t *testing.T) {
	// Arrange: a real submit is outstanding when the CLI writes its bookkeeping.
	h := newQueueHarness(t, nil)
	if err := h.submitAs("r1", "hello there"); err != nil {
		t.Fatalf("submit: %v", err)
	}

	// Act: the machinery record arrives BEFORE the real prompt's durable line.
	h.controller().consumer.Consume(transcriptUserEvent(t, 12, "u-machinery", compactMachinery))

	// Assert: nothing is drawn. The user is still waiting for their own prompt's
	// line, and a machinery record rendered in its place would read as it.
	if turns := h.userTurns(); len(turns) != 0 {
		t.Fatalf("pushed %d user turn(s) for a machinery record, want none", len(turns))
	}
}

func TestTheRealLineStillRendersAfterAMachineryLine(t *testing.T) {
	// Arrange
	h := newQueueHarness(t, nil)
	if err := h.submitAs("r1", "hello there"); err != nil {
		t.Fatalf("submit: %v", err)
	}

	// Act
	h.controller().consumer.Consume(transcriptUserEvent(t, 12, "u-machinery", compactMachinery))
	h.controller().consumer.Consume(transcriptUserEvent(t, 13, "u-real", "hello there"))

	// Assert
	turns := h.userTurns()
	if len(turns) != 1 {
		t.Fatalf("pushed %d user turn(s), want the real durable line alone", len(turns))
	}
	if got := turns[0].item.GetUuid(); got != "u-real" {
		t.Errorf("rendered uuid = %q, want the real prompt's own line", got)
	}
}

func TestAReplayedMachineryLineIsNeverDrawnAsAPromptEither(t *testing.T) {
	// Arrange: a resync must not re-pollute a feed the live path kept clean.
	h := newQueueHarness(t, nil)

	// Act
	h.controller().consumer.pushConversation(transcriptUserEvent(t, 12, "u-machinery", compactMachinery), false)

	// Assert
	if turns := h.userTurns(); len(turns) != 0 {
		t.Fatalf("replayed %d user turn(s) for a machinery record, want none", len(turns))
	}
}

// machineryStreamEvent is the same bookkeeping arriving on the STREAM plane
// (a bare UserMessage rather than a transcript line).
func machineryStreamEvent(t *testing.T, seq uint64, text string) *corev1.Event {
	t.Helper()
	a, err := anypb.New(&datav1.UserMessage{
		Message: &datav1.ApiUserMessage{
			Content: &datav1.ApiUserMessage_ContentString{ContentString: text},
		},
	})
	if err != nil {
		t.Fatalf("anypb.New: %v", err)
	}
	return &corev1.Event{SessionId: "vendor-uuid", Seq: seq, Payload: &corev1.Event_Vendor{Vendor: a}}
}

func TestMachineryOnTheStreamPlaneIsNeverDrawnAsAPromptEither(t *testing.T) {
	// Arrange
	h := newQueueHarness(t, nil)

	// Act
	h.controller().consumer.Consume(machineryStreamEvent(t, 12, compactMachinery))

	// Assert
	if turns := h.userTurns(); len(turns) != 0 {
		t.Fatalf("pushed %d user turn(s) for a stream-plane machinery record, want none", len(turns))
	}
}

// --- outbound classification ------------------------------------------------

// shapeAPromptEvent is the CLI's SHAPE A synthetic record as the file plane
// delivers it: a "user" transcript line, NOT flagged isMeta, carrying the
// promptId that groups one submission's records.
func shapeAPromptEvent(t *testing.T, seq uint64, uuid, promptID, text string) *corev1.Event {
	t.Helper()
	a, err := anypb.New(&datav1.TranscriptLine{
		Line: &datav1.TranscriptLine_User{User: &datav1.UserLine{
			Envelope: &datav1.LineEnvelope{Uuid: uuid, PromptId: promptID},
			Message: &datav1.ApiUserMessage{
				Content: &datav1.ApiUserMessage_ContentString{ContentString: text},
			},
		}},
	})
	if err != nil {
		t.Fatalf("anypb.New: %v", err)
	}
	return &corev1.Event{SessionId: "vendor-uuid", Seq: seq, Payload: &corev1.Event_Vendor{Vendor: a}}
}

// shapeBLocalCommandEvent is the CLI's SHAPE B synthetic record: a "system"
// line with subtype local_command, flagged isMeta and carrying NO promptId.
func shapeBLocalCommandEvent(t *testing.T, seq uint64, uuid, content string) *corev1.Event {
	t.Helper()
	a, err := anypb.New(&datav1.TranscriptLine{
		Line: &datav1.TranscriptLine_System{System: &datav1.SystemLine{
			Envelope: &datav1.LineEnvelope{Uuid: uuid, IsMeta: true},
			Subtype:  &datav1.SystemLine_LocalCommand{LocalCommand: &datav1.LocalCommandLine{Content: content}},
		}},
	})
	if err != nil {
		t.Fatalf("anypb.New: %v", err)
	}
	return &corev1.Event{SessionId: "vendor-uuid", Seq: seq, Payload: &corev1.Event_Vendor{Vendor: a}}
}

// classifiedCommands returns every DaemonInterceptedCommandItem the consumer
// pushed on the conversation plane, keyed by the record uuid it rode on.
func (h *queueHarness) classifiedCommands() map[string]frontendv1.SessionCommand {
	h.push.mu.Lock()
	defer h.push.mu.Unlock()
	out := map[string]frontendv1.SessionCommand{}
	for _, cd := range h.push.convo {
		for _, it := range cd.GetMessages() {
			if dic := it.GetDaemonInterceptedCommand(); dic != nil {
				out[it.GetUuid()] = dic.GetCommand()
			}
		}
	}
	return out
}

func TestShapeAIsClassifiedByItsContentHead(t *testing.T) {
	// Arrange: shape A's envelope says nothing, so the head is the only signal.
	h := newQueueHarness(t, nil)

	// Act
	h.controller().consumer.Consume(shapeAPromptEvent(t, 12, "u-a", "prompt-1", compactMachinery))

	// Assert
	got := h.classifiedCommands()
	if got["u-a"] != frontendv1.SessionCommand_SESSION_COMMAND_COMPACT {
		t.Errorf("classified command for u-a = %v, want COMPACT", got["u-a"])
	}
}

func TestShapeBIsClassifiedByItsEnvelopeNotItsContentHead(t *testing.T) {
	// Arrange: a system/local_command record whose body opens with ordinary
	// stdout — no machinery prefix at all — so only the envelope can decide it.
	h := newQueueHarness(t, nil)
	body := "Context Usage\n<command-name>/context</command-name>\n"

	// Act
	h.controller().consumer.Consume(shapeBLocalCommandEvent(t, 12, "u-b", body))

	// Assert
	got := h.classifiedCommands()
	if got["u-b"] != frontendv1.SessionCommand_SESSION_COMMAND_CONTEXT {
		t.Errorf("classified command for u-b = %v, want CONTEXT from the envelope test", got["u-b"])
	}
}

func TestAHumanPromptQuotingAMachineryTagStaysAPrompt(t *testing.T) {
	// Arrange: the regression guard on head-only matching.
	h := newQueueHarness(t, nil)
	prose := "why does the transcript contain <command-name>/compact</command-name> records?"

	// Act
	h.controller().consumer.Consume(shapeAPromptEvent(t, 12, "u-human", "prompt-1", prose))

	// Assert
	if got := h.classifiedCommands(); len(got) != 0 {
		t.Fatalf("classified %d command(s) from a human prompt, want none", len(got))
	}
	turns := h.userTurns()
	if len(turns) != 1 || turns[0].item.GetUuid() != "u-human" {
		t.Fatalf("pushed %d user turn(s), want the human prompt untouched", len(turns))
	}
}

func TestTwoCloseTogetherCommandsKeepTheirOwnIdentities(t *testing.T) {
	// Arrange: two commands in adjacent records, each with its own promptId.
	h := newQueueHarness(t, nil)
	clearMachinery := "<command-message>clear</command-message>\n<command-name>/clear</command-name>"

	// Act
	h.controller().consumer.Consume(shapeAPromptEvent(t, 12, "u-compact", "prompt-1", compactMachinery))
	h.controller().consumer.Consume(shapeAPromptEvent(t, 13, "u-clear", "prompt-2", clearMachinery))

	// Assert: each command rides its OWN record's uuid, so nothing about the
	// verdict depends on the order the two arrived in.
	got := h.classifiedCommands()
	if got["u-compact"] != frontendv1.SessionCommand_SESSION_COMMAND_COMPACT {
		t.Errorf("classified command for u-compact = %v, want COMPACT", got["u-compact"])
	}
	if got["u-clear"] != frontendv1.SessionCommand_SESSION_COMMAND_CLEAR {
		t.Errorf("classified command for u-clear = %v, want CLEAR", got["u-clear"])
	}
}

// classifiedItem returns the classified DaemonInterceptedCommandItem message
// pushed on the conversation plane under uuid, or nil when none was.
//
// The whole MESSAGE rather than just its command, because the durability arm is
// what these tests are about and the command alone cannot state it.
func (h *queueHarness) classifiedItem(uuid string) *frontendv1.Message {
	h.push.mu.Lock()
	defer h.push.mu.Unlock()
	for _, cd := range h.push.convo {
		for _, it := range cd.GetMessages() {
			if it.GetUuid() == uuid && it.GetDaemonInterceptedCommand() != nil {
				return it
			}
		}
	}
	return nil
}

func TestAClassifiedShapeAIsDurable(t *testing.T) {
	// Arrange: shape A has a transcript record behind it, so it must CLAIM one.
	h := newQueueHarness(t, nil)

	// Act
	h.controller().consumer.Consume(shapeAPromptEvent(t, 12, "u-a", "prompt-1", compactMachinery))

	// Assert
	it := h.classifiedItem("u-a")
	if it == nil {
		t.Fatal("no classified item for u-a")
	}
	if it.GetDurable() == nil {
		t.Errorf("classified shape A durability arm = %v, want DURABLE — the CLI wrote a transcript record for it", it.GetDurability())
	}
}

func TestAClassifiedShapeBIsEphemeral(t *testing.T) {
	// Arrange: shape B carries no promptId and the contract rules it out of the
	// durable set, so it must claim NO record.
	h := newQueueHarness(t, nil)

	// Act
	h.controller().consumer.Consume(shapeBLocalCommandEvent(t, 12, "u-b", "<command-name>/context</command-name>"))

	// Assert
	it := h.classifiedItem("u-b")
	if it == nil {
		t.Fatal("no classified item for u-b")
	}
	if it.GetEphemeral() == nil {
		t.Errorf("classified shape B durability arm = %v, want EPHEMERAL", it.GetDurability())
	}
}

func TestAClassifiedEphemeralCommandIsAFeedRow(t *testing.T) {
	// Arrange: rule 1 — an ephemeral message is ALWAYS a feed row, and the
	// constructor is what makes that true of a classified record too.
	h := newQueueHarness(t, nil)

	// Act
	h.controller().consumer.Consume(shapeBLocalCommandEvent(t, 12, "u-b", "<command-name>/context</command-name>"))

	// Assert
	it := h.classifiedItem("u-b")
	if it == nil {
		t.Fatal("no classified item for u-b")
	}
	if got := it.GetLineage().GetParentMessageId(); got != "" {
		t.Errorf("ephemeral classified item parent_message_id = %q, want none", got)
	}
	if got := it.GetLineage().GetTopLevelMessageId(); got != "u-b" {
		t.Errorf("ephemeral classified item top_level_message_id = %q, want its own uuid", got)
	}
}

// blockUserTranscriptEvent is a user transcript line whose body arrives as
// content BLOCKS — the shape the real file plane produces for a typed prompt,
// as opposed to the single content string a hand-simplified fixture uses.
func blockUserTranscriptEvent(t *testing.T, seq uint64, uuid, promptID string, texts ...string) *corev1.Event {
	t.Helper()
	blocks := make([]*datav1.ContentBlock, 0, len(texts))
	for _, txt := range texts {
		blocks = append(blocks, &datav1.ContentBlock{
			Block: &datav1.ContentBlock_Text{Text: &datav1.TextBlock{Text: txt}},
		})
	}
	a, err := anypb.New(&datav1.TranscriptLine{
		Line: &datav1.TranscriptLine_User{User: &datav1.UserLine{
			Envelope: &datav1.LineEnvelope{Uuid: uuid, PromptId: promptID},
			Message: &datav1.ApiUserMessage{
				Content: &datav1.ApiUserMessage_ContentBlocks{
					ContentBlocks: &datav1.ApiContentBlocks{Blocks: blocks},
				},
			},
		}},
	})
	if err != nil {
		t.Fatalf("anypb.New: %v", err)
	}
	return &corev1.Event{SessionId: "vendor-uuid", Seq: seq, Payload: &corev1.Event_Vendor{Vendor: a}}
}

func TestAHumanPromptOpeningWithAnUnclosedMachineryTagStaysAPrompt(t *testing.T) {
	// Arrange: the user asks ABOUT the tag and starts the sentence with it, so
	// the head opens with machinery markup that is never closed. An opening tag
	// alone is not machinery-ness, and treating it as such destroyed the prompt.
	h := newQueueHarness(t, nil)
	prose := "<command-name> keeps showing up in my transcript, what writes it?"

	// Act
	h.controller().consumer.Consume(blockUserTranscriptEvent(t, 12, "u-human", "prompt-1", prose))

	// Assert
	if got := h.classifiedCommands(); len(got) != 0 {
		t.Fatalf("classified %d command(s) from a human prompt, want none", len(got))
	}
	turns := h.userTurns()
	if len(turns) != 1 || turns[0].item.GetUuid() != "u-human" {
		t.Fatalf("pushed %d user turn(s), want the human prompt untouched", len(turns))
	}
}

func TestAMachineryRecordSpanningBlocksIsStillClassified(t *testing.T) {
	// Arrange: a caveat wrapper that opens in the first block and closes in the
	// second — the balance test must read the whole body, not just the head.
	h := newQueueHarness(t, nil)

	// Act
	h.controller().consumer.Consume(blockUserTranscriptEvent(t, 12, "u-split", "prompt-1",
		"<local-command-caveat>Caveat: the messages below",
		"were generated while running local commands.</local-command-caveat>",
		"<command-name>/compact</command-name>"))

	// Assert
	got := h.classifiedCommands()
	if got["u-split"] != frontendv1.SessionCommand_SESSION_COMMAND_COMPACT {
		t.Errorf("classified command for u-split = %v, want COMPACT", got["u-split"])
	}
}
